### ISSUE TITLE
ns-render-mesh crashing, `load_from_json`

### ISSUE THREAD

**Issue by pablovela5620** [autonomousvision/sdfstudio#1]
**Describe the bug**
Trying to render a mesh following what was described on the README

**To Reproduce**
After generating mesh, used the command
`ns-render-mesh --meshfile meshes/neus-facto-dtu65.ply --traj interpolate --data.data data/sdfstudio-demo-data/dtu-scan65 --output-path renders/neus-facto-dtu65.mp4`

get the following error
```
Creating trajectory video
[Open3D WARNING] GLFW Error: X11: The DISPLAY environment variable is missing
[Open3D WARNING] Failed to initialize GLFW
Traceback (most recent call last):
  File "/home/pablo/miniconda3/envs/sdfstudio/bin/ns-render-mesh", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/pablo/0Dev/repos/sdfstudio/scripts/render_mesh.py", line 246, in entrypoint
    tyro.cli(RenderTrajectory).main()
  File "/home/pablo/0Dev/repos/sdfstudio/scripts/render_mesh.py", line 231, in main
    _render_trajectory_video(
  File "/home/pablo/0Dev/repos/sdfstudio/scripts/render_mesh.py", line 103, in _render_trajectory_video
    vis.get_render_option().load_from_json("scripts/render.json")
AttributeError: 'NoneType' object has no attribute 'load_from_json'
```

**Expected behavior**

Should be outputting an mp4

**Screenshots**

**Additional context**
This is on a remote machine using vscode with ssh. Not sure if that's relevant or not

also congrats on the release! I'm excited to use this library, it was exactly what I was looking for.

**Comment by niujinshuchong** [comment]
@pablovela5620 I think this is because the prebuilt opend3d doesn't support headless rendering. Could you try following [here](http://www.open3d.org/docs/release/tutorial/visualization/headless_rendering.html#) to build open3d from source with headless rendering supports.

**Comment by pablovela5620** [comment]
I will give this a try, thanks for your suggestion
