### ISSUE TITLE
Texture mesh quality is bad

### ISSUE THREAD

**Issue by nangongliufeng** [autonomousvision/sdfstudio#106]
The exported texture mesh has cracks, how to adjust？
![图片](https://user-images.githubusercontent.com/87115602/236363433-3e4e5463-1bec-4900-8b4c-0dde92f3e155.png)

**Comment by niujinshuchong** [comment]
Hi, how do you extract the mesh? do you use `ns-extract-mesh`? which model did you use? This issue might be helpful https://github.com/autonomousvision/sdfstudio/issues/82
