### ISSUE TITLE
installation of open3d/0.16.0

### ISSUE THREAD

**Issue by TianyuHuang-000** [autonomousvision/sdfstudio#107]
Anyone has idea how to install open3d/0.16.0?
<img width="1512" alt="截屏2023-05-05 下午1 10 23" src="https://user-images.githubusercontent.com/88012819/236385926-4d476ab1-80a3-4426-b068-0805b6dd0f47.png">

**Comment by niujinshuchong** [comment]
Hi, this might depends on the your system. Ubuntu system can install open3d/0.16.0 easily but for other system you might need to compile open3d yourself. Currently open3d is only used for mesh rendering, you can skip installing open3d if you are not going to use mesh rendering.
