### ISSUE TITLE
Add a new method

### ISSUE THREAD

**Issue by bxcharlie** [autonomousvision/sdfstudio#108]
Thank you for your great work!
But I don't see in your documentation how i can add a new method

I tried the same method as nerfstudio [Adding a new method by nerfstudio](https://docs.nerf.studio/en/latest/developer_guides/new_methods.html)，But the new method was not successfully registered

The name of the new method I want to add is sdfmethod，When I runned `pip install -e .`，it tips successfully installed sdfmethod-0.0.1：
![image](https://user-images.githubusercontent.com/48048573/236719705-d61e5e7b-c408-4325-8e4e-83ca8711d56b.png)

I can see in pip list really have this
![image](https://user-images.githubusercontent.com/48048573/236719987-37587a4b-5ba0-44ec-8935-b0801914621d.png)

but，when I run `ns-train sdfmethod --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-dtu65 sdfstudio-data --data data/sdfstudio-demo-data/dtu-scan65`，It prompts that there is no new method named `sdfmethod` I have added
![image](https://user-images.githubusercontent.com/48048573/236720831-c72d87aa-e2fc-4207-93ce-3f45017ef2f1.png)

Does sdfstudio have its own process for adding new methods?

**Comment by niujinshuchong** [comment]
@bxcharlie Currently adding new methods like nerfstudio is unfortunately not supported because this features is added very recently to nerfstudio and sdfstudio is built upon an earlier version of nerfstudio. You need to edit the sdfstudio code directly for adding new methods.

**Comment by bxcharlie** [comment]
Thank you for your solution！Can you elaborate on which part of the code needs to edit to use `ns-train`?

**Comment by bxcharlie** [comment]
I am sorry but when I add the following code 
```
method_configs["new-method"] = Config(
    method_name="new-method",
    trainer=TrainerConfig(
        steps_per_eval_image=5000,
    ),
    viewer=ViewerConfig(num_rays_per_chunk=1 << 15),
    vis="viewer",
)
```
to nerfstudio/configs/method_configs.py, then I test `ns-train -h` on sdfstudio,  I can't find `new-method`
![image](https://github.com/autonomousvision/sdfstudio/assets/48048573/5a27dcc4-9fc2-4ed3-8894-8bb65b88fe3a)


And I have tested the same way on nerfstudio, it will prompt the `new-method`
![image](https://github.com/autonomousvision/sdfstudio/assets/48048573/092be18a-87e3-4176-9c17-4f4fede539c7)

I wonder what else I need to do to see `new-method` when running `ns-train-h`.
Thank you very much!

**Comment by niujinshuchong** [comment]
Hi, I simply added your code and it works.

![Screenshot from 2023-05-12 11-11-05](https://github.com/autonomousvision/sdfstudio/assets/13434986/3a214bc0-aebc-4743-aab9-b4ae861c0716)

**Comment by bxcharlie** [comment]
Thanks！I found that there was something wrong with the environment，and it works now.
