### ISSUE TITLE
Mask on DTU dataset

### ISSUE THREAD

**Issue by rspezialetti** [autonomousvision/sdfstudio#11]
Hi, congratulations for this great work. I have tried to train NeUS on a sample of DTU dataset. However, I get the following results:

![image](https://user-images.githubusercontent.com/16280106/209841538-31b425ac-4986-496c-a520-18569631e324.png)

Is there any way to train using background masks as well ?
Bests,

Riccardo

**Comment by niujinshuchong** [comment]
Hi, do you want to filter out the table region?

**Comment by rspezialetti** [comment]
Hi,
thank you for your reply. In NeUS original paper they have two configurations: one with mask and one without. I'd like to run your implementation using the first configuration.

Bests,
Riccardo

**Comment by niujinshuchong** [comment]
I see. Currently the meta_data.json in DTU dataset don't have the mask. Will try to update it soon.

**Comment by niujinshuchong** [comment]
Hi, the foreground masks are added to the dtu dataset. You need to download the latest data and code. It can be run with
```
ns-train neus --pipeline.model.sdf-field.use-grid-feature False --pipeline.model.sdf-field.hidden-dim 256 --pipeline.model.sdf-field.num-layers 8 --pipeline.model.sdf-field.num-layers-color 4 --pipeline.model.sdf-field.use-appearance-embedding False --pipeline.model.sdf-field.geometric-init True --pipeline.model.sdf-field.inside-outside False  --pipeline.model.sdf-field.bias 0.5 --pipeline.model.sdf-field.beta-init 0.3 --trainer.steps-per-eval-image 5000 --pipeline.datamanager.train-num-rays-per-batch 1024 --pipeline.model.background-model mlp --pipeline.model.fg-mask-loss-mult 0.1 --vis wandb --experiment-name neus-dtu114  sdfstudio-data --data data/dtu/scan65 --include_foreground_mask True
```

**Comment by rspezialetti** [comment]
it works like a charm!
Thank you
