### ISSUE TITLE
Can't get reasonable results from data that nerfstudio aces?

### ISSUE THREAD

**Issue by xiumingzhang** [autonomousvision/sdfstudio#114]
I've been struggling to attain reasonable results for my custom nerfstudio-like data, similar to https://github.com/autonomousvision/sdfstudio/issues/49, https://github.com/autonomousvision/sdfstudio/issues/85, etc., so I took a step back:  What if I just take nerfstudio's example "poster" dataset (which nerfstudio aces) and directly run sdfstudio on it? It turned out I was unable to get reasonable results for that dataset either.

1. Download nerfstudio's poster dataset.
2. Run, say, neus-facto with the `nerfstudio-data` data parser.
3. Look at the tensorboard results.

One example full command:
```bash
method=neus-facto
ns-train \
    $method \
    --pipeline.model.sdf-field.inside-outside True \
    --pipeline.model.background-model mlp \
    --output-dir sdfstudio_train/nerfstudio_data/poster/ \
    --method-name $method \
    --experiment-name sanity-check-mlp-bg-focus-vertical \
    --vis tensorboard \
    nerfstudio-data \
    --data nerfstudio/data/nerfstudio/poster \
    --center-method focus \
    --orientation-method vertical
```

I tried numerous combinations of:
- `--pipeline.model.background-model mlp`
- `--pipeline.model.sdf-field.inside-outside True`
- Patching this PR: https://github.com/autonomousvision/sdfstudio/pull/90
- `--pipeline.model.sdf-field.use-grid-feature False`
- `--pipeline.model.far-plane 2.0`
- `--pipeline.model.sdf-field.num-layers 8`
- `--pipeline.model.enable-collider False`

Example failures:
![image](https://github.com/autonomousvision/sdfstudio/assets/11436350/47d3ddf6-6cde-4cea-bb4c-91a8fc8e797e)

![image](https://github.com/autonomousvision/sdfstudio/assets/11436350/fff91ce9-b5ba-4933-9149-f99450d9f430)

![image](https://github.com/autonomousvision/sdfstudio/assets/11436350/f9c3af9c-3d5a-4a91-b0cd-dfc001400a15)

What am I missing? Thanks in advance for thoughts/suggestions.

**Comment by xiumingzhang** [comment]
Thanks for the prompt help. I got similar results with your command on this poster scene. One quick follow-up question: Why `--pipeline.model.sdf-field.inside-outside False`? The CLI help said one should set it to `True` for indoor scenes.

**Comment by niujinshuchong** [comment]
I thought this is a 360 inward scene so I use `--pipeline.model.sdf-field.inside-outside False` where the wall of the room is modelled as background. Using `--pipeline.model.sdf-field.inside-outside True` might also works.

**Comment by fafancier** [comment]
@xiumingzhang  I got simlilar error.  under same data, nerfacto can export correct pointcloud. however nues facto can't.
the pointcloud seems constitute an circle around center.
have you figure out the solution? many thx.
