### ISSUE TITLE
About the influence of the near and far plane

### ISSUE THREAD

**Issue by niasie** [autonomousvision/sdfstudio#118]
I am trying to reconstruct outdoor environments from driving scenes using MonoSDF, and am a bit confused about how to correctly set the near and far plane.

On the one hand, I can see that there are the parameters “near” and “far” in the dataset [here](https://github.com/autonomousvision/sdfstudio/blob/master/scripts/datasets/process_nerfstudio_to_sdfstudio.py), lines 96-122.

However, SDFStudio also has command line arguments to change the (seemingly) same parameters:
```
 --pipeline.model.near-plane FLOAT
     How far along the ray to start sampling. (default: 0.05)
 --pipeline.model.far-plane FLOAT
     How far along the ray to stop sampling. (default: 4.0)
 --pipeline.model.far-plane-bg FLOAT
     How far along the ray to stop sampling of the background model.
     (default: 1000.0)
```

How exactly are these options related?

Also, what units are these parameters in, the units of the view locations, or units of the depth map? If I understand it correctly, the depth map does not have to correspond to the view locations in terms of scale, since the depth loss is scale-invariant. Am I right about that?

Currently, my dataset looks like this in the viewer:
<img width="1800" alt="image" src="https://github.com/autonomousvision/sdfstudio/assets/9141779/3b9c1223-1ef2-4c35-b3bf-cd2fb9fc7741">

Am I right that the scene box is too large?

For reference, this is what I use to start training:
```
ns-train monosdf \
--output-dir ./output \
--trainer.steps-per-save 5000 \
--trainer.max-num-iterations 200000 \
--trainer.steps-per-eval-image 1000 \
--pipeline.model.sdf-field.inside-outside True \
--pipeline.model.sdf-field.use-grid-feature True \
--pipeline.model.background-model grid \
--pipeline.datamanager.train-num-images-to-sample-from 1 \
--pipeline.datamanager.train-num-times-to-repeat-images 0 \
--vis viewer  \
--experiment-name poster-${SCENE_NAME}-$(date +%F_%T) \
sdfstudio-data \
--data /cluster/project/infk/courses/252-0579-00L/group26/sniall/kitti/datasets_paper/${SCENE_NAME} \
--auto-orient True \
--include-mono-prior True
```

I would be thankful for some advice on this.

**Comment by niujinshuchong** [comment]
Hi, the command line arguments can overwrite the near and far values in the dataset (you also need to set `--pipeline.model.overwrite-near-far-plane True`) . You can set an approximate near and far values by observing the camera distribution in the viewer. The unit is related to the unit cube that you saw in the viewer. The near and far value is dataset dependent so the preprocessing script might not work well for your dataset. You could normalize the poses such that the main scene content lies between the unit cube.

From your screenshot, seems like the whole scene only occupies a small part of the unit cube and might be better to scale it.

**Comment by niasie** [comment]
Hi, thank you very much for your reply! I will take your recommendations into consideration.
