### ISSUE TITLE
Questions of the depth data 

### ISSUE THREAD

**Issue by moyutianque** [autonomousvision/sdfstudio#122]
Here is a calculation (depth_gt * 50 + 0.5) before depth loss in mono-prior. Does anyone know what is 50 and 0.5 in the following line. Isn't the depth value stored in meter?

[link](https://github.com/autonomousvision/sdfstudio/blob/df93681faf8e7fb58f86e61c2bd9744ba88fa025/nerfstudio/models/base_surface_model.py#L401)

**Comment by niujinshuchong** [comment]
Hi, the monocular depth is up to scale. Please refer to https://github.com/autonomousvision/monosdf/issues/18. The value is chosen based on the replica dataset which might not work well for other datasets.

**Comment by moyutianque** [comment]
thanks for the information, could I know how this value was designed? I tried depth extracted from omnidata with script [link](https://github.com/autonomousvision/sdfstudio/blob/master/scripts/datasets/process_nerfstudio_to_sdfstudio.py) in sdfstudio on my dataset collected from matterport simulator. But it does not perform well, it will grateful if you can give suggestions on how to tune these values.

**Comment by niujinshuchong** [comment]
Hi, I adjusted the scale and shift based the omnidata model's output such that the range is in [0, 2]. But it also interleaves with monocular depth loss weight in the loss function. You might need to try different values. Can you share some of your results? Did you also try monocular normal loss?

**Comment by moyutianque** [comment]
Thanks. 

After further testing (change to gt depth and modify the loss calculation), I found the poses transferred from nerfstudio to sdfstudio dataset cause the main issue. May I ask why args.scene_scale_mult in [process_nerfstudio_to_sdfstudio.py](https://github.com/autonomousvision/sdfstudio/blob/master/scripts/datasets/process_nerfstudio_to_sdfstudio.py) are set to 5 for indoor scene? From the viewer, if set to 5, all cameras are very centered in a small region in the scene_box, but it seems its performance is better than set args.scene_scale_mult to 4,3,2,1.

**Comment by moyutianque** [comment]
Thanks, I try to change the scale of my poses in nerfstudio transforms.json to match meta_data.json scale, it performs well now. But I found in [process_nerfstudio_to_sdfstudio.py](https://github.com/autonomousvision/sdfstudio/blob/master/scripts/datasets/process_nerfstudio_to_sdfstudio.py#L81) the scale for indoor scene is set to 5, **is there any insight of this number?** I tried args.scene_scale_mult=2 which makes poses more sparse within the scene-box the performance drops 4 psnr in the end.

**Comment by niujinshuchong** [comment]
Hi, the value is chosen based on a very specific scene so it might not work well for your data. You need to normalize your poses such that the main object is inside the unit cube. Maybe you could also try this one: https://github.com/autonomousvision/sdfstudio/pull/90. Btw, if you are using monocular prior, you could try to enable only normal loss or only depth loss to compare the differences. Normal is usually more robust.

**Comment by moyutianque** [comment]
OK thanks.
