### ISSUE TITLE
How much memory is required to execute the BakedSDF model?

### ISSUE THREAD

**Issue by xiemeilong** [autonomousvision/sdfstudio#130]
**Describe the bug**
My computer has 32GB of memory. When training the BakedSDF model with 180 images, it gets killed each time due to insufficient memory. However, I can train nerfacto with the same data in nerfstudio without any issues.

**To Reproduce**
ns-train bakedsdf  --data data/sdfstudio/tangtousimple --output-dir outputs/sdf/tangtousimple

**Expected behavior**
Not killed

**Screenshots**
![image](https://github.com/autonomousvision/sdfstudio/assets/2681638/aff32784-63ef-40d0-b6fe-ed62aed99986)

**Additional context**
Run in docker container with image compiled by the dockerfile. There is no memory limit on the container.

**Comment by MvWouden** [comment]
What's the resolution of the images? I've had no issue loading in 300 1080p images with 16GB RAM. That running directly and not in a docker container though.

**Comment by 440981** [comment]
I also encountered this problem. How did you solve it?

**Comment by xiemeilong** [comment]
@440981 Use the downscaled images
