### ISSUE TITLE
Problems about the derivation of adding mono prior depth in base_surface_model

### ISSUE THREAD

**Issue by llcc343** [autonomousvision/sdfstudio#132]
In base_surface_model.py L252 converting point to point depth to camera coord depth, you simply divide the ray bundle direction norm. The ray bundle direction norm is much different from the depth scale in the original monosdf, is here a potential bugs?

**Comment by niujinshuchong** [comment]
Hi, please refer to https://github.com/autonomousvision/monosdf/issues/22#issuecomment-1276294258.
