### ISSUE TITLE
Voxurf implementation

### ISSUE THREAD

**Issue by vgrau98** [autonomousvision/sdfstudio#136]
Hello,

I have some questions regarding Voxurf surface reconstruction method:
https://github.com/wutong16/Voxurf

1. Does sdfstudio support explicit volumetric field (sdf grid for instance) ? 
2. Does sdfstudio support mask generation from a first density field (cf init coarse geometry extraction from DVGO - https://github.com/sunset1995/DirectVoxGO - in the voxurf method) to further optimized ray sampling ? 

I've looked at the code and can't seem to find any similar features in the various modules
Thank you !

**Comment by niujinshuchong** [comment]
@vgrau98 Currently sdfstudio don't support explicit grid. But we have `neus-acc` which uses nerfacc to speed up the sampling by an occupancy grid.

**Comment by vgrau98** [comment]
Thank you for you answer @niujinshuchong
