### ISSUE TITLE
Misunderstanding  of installation

### ISSUE THREAD

**Issue by XinyueZ** [autonomousvision/sdfstudio#137]
Hey guys, may you help me? just see the comment in the readme about installing, I got confusion:

"SDFStudio is built on top of [nerfstudio](https://github.com/nerfstudio-project/nerfstudio). If you have already installed the nerfstudio environment, you can skip the following steps."

- "the following steps" -> from where,  which step, and to where?

- I have the latest Nerfstudio installed, does the state-quo of sdstudio work for it?

thanks

**Comment by niujinshuchong** [comment]
Hi, sdfstudio is based on a very early version of nerfstudio. And nerfstudio had many changes since then, I think it's better to create a new environment for sdfstudio.

**Comment by XinyueZ** [comment]
@niujinshuchong  I think you guys should address this in the readme, otherwise, the user will struggle so much with installation sutff.

thx

**Comment by niujinshuchong** [comment]
It's updated. Thanks for the suggestion.
