### ISSUE TITLE
KeyError: 'field_background' when training BakedSDF with blender dataset

### ISSUE THREAD

**Issue by kkennethwu** [autonomousvision/sdfstudio#138]
Hi, thanks for your great work, I try to train bakedSDF in ship dataset of blender data with following cmd:

ns-train bakedsdf --vis viewer --experiment-name ship-bakedsdf blender-data --data data/blender/ship

And, there is an error in optimizer.py => KeyError: 'field_background'
<img width="556" alt="截圖 2023-06-20 下午5 20 14" src="https://github.com/autonomousvision/sdfstudio/assets/71262989/5beec55b-86e3-47db-ac88-9e5a4c74345e">

**Comment by niujinshuchong** [comment]
Hi, this should be fixed in the latest commit. Please try again.

**Comment by kkennethwu** [comment]
> Hi, this should be fixed in the latest commit. Please try again.

Oh it works! Big Thanks!


> I think it's better that you also change the near and far plane, default background color, and disable appearance embedding for the nerf-synthetic dataset with `--pipeline.model.near-plane 2 --pipeline.model.far-plane 6 --pipeline.model.overwrite-near-far-plane True --pipeline.model.background-color white --pipeline.model.sdf-field.use-appearance-embedding False`.

I see. Thanks for your advice !
