### ISSUE TITLE
meta_data.json not found  

### ISSUE THREAD

**Issue by XinyueZ** [autonomousvision/sdfstudio#139]
Hey guys,

I used `ns-process-data` to generate images from a video.

I was trying to run `ns-train neuralangelo --data .....`

I got error: `No such file or directory: '/home/user/sdfstudio/data/....../meta_data.json'`

Did I forget something?

thanks

**Comment by niujinshuchong** [comment]
Hi, `ns-process-data` generates data in nerfstudio format. You need to use the nerfstudio-data parser for it. For example, 
`ns-train xxx nerfstudio-data --data your_data`.
