### ISSUE TITLE
`neuralangelo` / `neus-facto-angelo` training is very slow

### ISSUE THREAD

**Issue by nlml** [autonomousvision/sdfstudio#140]
Thanks for adding the neuralangelo method so quickly!

One thing I noticed on a first test though - the training rays/sec for `neus-facto-angelo` is about 25x slower than `neus-facto`.

Any idea on why this is? I might try to address this but curious if anyone else is looking into it.

Thanks!

**Comment by XinyueZ** [comment]
same question here.

**Comment by niujinshuchong** [comment]
Hi, `neus-facto-angelo` uses multi-res. hash encoding with much more learnable parameters (~30x more) and a slightly bigger MLP (4 layers vs 2 layers). The hash encoding will be very slow if the GPU cache is not big enough. You could try to use the same hash encoding parameters and compare the differences.

**Comment by nlml** [comment]
Thanks for your reply. That's interesting. I actually got quite bad results on dtu scan65 with the `neus-facto-angelo` default settings. Plus it crashed at around the 60% mark. `neuralangelo` on the other hand produced very nice-looking results. I'll play around with what you suggest and report back!

**Comment by nlml** [comment]
If anyone's interested, on DTU scan 65, I get better results than `neus-facto` (PSNR of around 36 vs. 32) with a similar parameter count and 20k iterations using the following modified version of `neus-facto-angelo`:

```python
ns-train neus-facto-angelo \
    --trainer.max-num-iterations 20001 \
    --pipeline.model.sdf-field.inside-outside False \
    --pipeline.model.sdf-field.num-layers-color 2 \
    --pipeline.model.sdf-field.log2-hashmap-size 18 \
    --pipeline.model.sdf-field.hash-features-per-level 4 \
    --pipeline.model.sdf-field.base-res 16 \
    --pipeline.model.sdf-field.max-res 2048 \
    --pipeline.model.steps-per-level 800 \
    --pipeline.model.sdf-field.use-appearance-embedding True \
    --pipeline.model.sdf-field.use-position-encoding True \
    --vis tensorboard \
    --experiment-name neus-facto-angelo-improve \
    sdfstudio-data --data dtu-scan65
```

To get this result you'll also need to change the learning rate schedule in the method config for neus-facto-angelo to match the reduced number of iterations:

```python
optimizers={
    "proposal_networks": {
        "optimizer": AdamOptimizerConfig(lr=1e-2, eps=1e-15),
        "scheduler": MultiStepSchedulerConfig(max_steps=20000),
    },
    "fields": {
        "optimizer": AdamOptimizerConfig(lr=1e-3, eps=1e-15),
        "scheduler": MultiStepWarmupSchedulerConfig(warm_up_end=100, milestones=[12500, 17500], gamma=0.1),
    },
    "field_background": {
        "optimizer": AdamWOptimizerConfig(lr=1e-3, eps=1e-15),
        "scheduler": MultiStepWarmupSchedulerConfig(warm_up_end=100, milestones=[12500, 17500], gamma=0.1),
    },
}
```

A few lessons learned here:
- `sdf-field.use-position-encoding` helps a lot
- reducing `log2-hashmap-size` reduces param count substantially without impacting performance, maybe can reduce further, probably depends on your scene though

I plan to keep exploring to try and quantify the benefits of the neuralangelo loss terms on neus-facto.

**Comment by shenggedeqiang** [comment]
> If anyone's interested, on DTU scan 65, I get better results than `neus-facto` (PSNR of around 36 vs. 32) with a similar parameter count and 20k iterations using the following modified version of `neus-facto-angelo`:
> 
> ```python
> ns-train neus-facto-angelo \
>     --trainer.max-num-iterations 20001 \
>     --pipeline.model.sdf-field.inside-outside False \
>     --pipeline.model.sdf-field.num-layers-color 2 \
>     --pipeline.model.sdf-field.log2-hashmap-size 18 \
>     --pipeline.model.sdf-field.hash-features-per-level 4 \
>     --pipeline.model.sdf-field.base-res 16 \
>     --pipeline.model.sdf-field.max-res 2048 \
>     --pipeline.model.steps-per-level 800 \
>     --pipeline.model.sdf-field.use-appearance-embedding True \
>     --pipeline.model.sdf-field.use-position-encoding True \
>     --vis tensorboard \
>     --experiment-name neus-facto-angelo-improve \
>     sdfstudio-data --data dtu-scan65
> ```
> 
> To get this result you'll also need to change the learning rate schedule in the method config for neus-facto-angelo to match the reduced number of iterations:
> 
> ```python
> optimizers={
>     "proposal_networks": {
>         "optimizer": AdamOptimizerConfig(lr=1e-2, eps=1e-15),
>         "scheduler": MultiStepSchedulerConfig(max_steps=20000),
>     },
>     "fields": {
>         "optimizer": AdamOptimizerConfig(lr=1e-3, eps=1e-15),
>         "scheduler": MultiStepWarmupSchedulerConfig(warm_up_end=100, milestones=[12500, 17500], gamma=0.1),
>     },
>     "field_background": {
>         "optimizer": AdamWOptimizerConfig(lr=1e-3, eps=1e-15),
>         "scheduler": MultiStepWarmupSchedulerConfig(warm_up_end=100, milestones=[12500, 17500], gamma=0.1),
>     },
> }
> ```
> 
> A few lessons learned here:
> 
> * `sdf-field.use-position-encoding` helps a lot
> * reducing `log2-hashmap-size` reduces param count substantially without impacting performance, maybe can reduce further, probably depends on your scene though
> 
> I plan to keep exploring to try and quantify the benefits of the neuralangelo loss terms on neus-facto.

Thanks for your trying！I repeat your practice above，but I can't get a correct mesh, the mesh is like this：
![C3_202307051552050252180120171197fd](https://github.com/autonomousvision/sdfstudio/assets/34940157/60a39eeb-aa9c-48e8-a87b-a1388a8477ff)
Why is this happening ？

**Comment by nlml** [comment]
I didn't try extracting a mesh. Do your results look good in the viewer or in the predicted RGB?

**Comment by nlml** [comment]
I'll close this for now, thanks again!

**Comment by amughrabi** [comment]
Hello @nlml, thank you for providing such valuable information. I was wondering if you could assist me with using masks in Neuralangelo during training. I have been trying to configure it but have been unsuccessful so far. Do you have any suggestions or tips?

**Comment by YvanYin** [comment]
Hello @nlml, have you successfully trained the  neuralangelo model? Could you share the training command?

**Comment by niujinshuchong** [comment]
Hi, you can use 
```bash
ns-train neuralangelo --vis wandb --experiment-name neuralangelo-dtu24-withbg  sdfstudio-data --data data/dtu/scan24 --load-dtu-highres True 
```
for training neuralangelo.

**Comment by nlml** [comment]
> Hello @nlml, have you successfully trained the neuralangelo model? Could you share the training command?

I believe the following worked for me:

```
ns-train neuralangelo --pipeline.model.sdf-field.inside-outside False --vis tensorboard --experiment-name neuralangelo-dtu65 sdfstudio-data --data dtu-scan65
```

It's been a while though.
