### ISSUE TITLE
How to add custom GUI ?

### ISSUE THREAD

**Issue by DevAgarwal-588** [autonomousvision/sdfstudio#142]
I want to try to add a custom GUI (dropdown menu on the web viewer). But, following the [custom GUI](https://docs.nerf.studio/en/latest/developer_guides/viewer/custom_gui.html) document of nerfstudio, I am getting errors like no module name vise, no viewer_elements, etc.

**Comment by niujinshuchong** [comment]
Hi, the viewer is developed by nerfstudio team and I am not sure how this custom GUI work.
