### ISSUE TITLE
Potential bug in SDFField

### ISSUE THREAD

**Issue by cdcseacave** [autonomousvision/sdfstudio#143]
Sorry if i misunderstood the code, but shouldn't be used `normals` instead of `gradients` [here](https://github.com/autonomousvision/sdfstudio/blob/ef14f965296a8e3b37ce21e51f1256be4868038f/nerfstudio/fields/sdf_field.py#L575)?

And in `get_outputs()` `self.spatial_distortion(inputs)` is done before calling `self.forward_geonetwork(inputs)`, but in many other places calling that function the spatial_distortion is not applied anymore. Is this intended?

**Comment by niujinshuchong** [comment]
Hi, we use `gradients` following IDR/volsdf. We also tested with `normal` but found the results are not as sharp as using `gradients`. You could refer to https://github.com/autonomousvision/sdfstudio/issues/54.

Yes, the `spatial_distortion` should be applied before the `forward_geonetwork`. The spatial_distortion is used only for BakedSDF where the background region is also modelled with a SDF field. For other methods the background regions are modelled by a different nerf network so this don't have a big difference. But yes, it might be better to restructure it.
