### ISSUE TITLE
How can I evaluate neuralangelo in RTK4090 without memory out error

### ISSUE THREAD

**Issue by byran-wang** [autonomousvision/sdfstudio#146]
**Describe the bug**
Thank you for your great work in sdfstudio, especially the latest work neuralangelo. However, I found that neuralangelo consume too much GPU memory when evaluation(no memory out error in trainning) which resulted in can not run in the RTK4090 with 24GB memory.

**To Reproduce**
The running command is: ns-train neuralangelo --experiment-name neuralangelo-truck-lego --vis wandb --trainer.steps-per-eval-image 200 --trainer.max-num-iterations 300001 --pipeline.datamanager.train-num-rays-per-batch 512 --pipeline.datamanager.eval-num-rays-per-batch 512 --pipeline.model.sdf-field.use-appearance-embedding False --pipeline.model.sdf-field.inside-outside False --pipeline.model.background-model none --pipeline.model.background-color white --pipeline.model.sdf-field.bias 0.1 --pipeline.model.level-init 4  blender-data --data ./nerf_synthetic/nerf_synthetic/lego

**Expected behavior**
No memory out error in both training and evaluation.

**Screenshots**
![cuda_momory_error](https://github.com/autonomousvision/sdfstudio/assets/16728958/fa40daf2-a14c-4037-b6bd-2665f350498a)

**Comment by JuliusQv** [comment]
Hello, I found that the `--pipeline.model.eval-num-rays-per-chunk` parameter may have a greater impact on GPU memory usage.
Also，I use the following commands which can run normally on the 32G V100:
 `ns-train neuralangelo  --trainer.steps-per-eval-batch 10000   --trainer.steps-per-eval-image 50000  --pipeline.model.sdf-field.inside-outside False    --pipeline.model.eval-num-rays-per-chunk 1024    --vis tensorboard `

**Comment by byran-wang** [comment]
Yes, neuralangelo evaluation can run normally without memory out error with your adviced setting  --pipeline.model.eval-num-rays-per-chunk 1024. 
Thank you very much.
