### ISSUE TITLE
How to reproduce the results in monosdf?

### ISSUE THREAD

**Issue by Vilour** [autonomousvision/sdfstudio#15]
I've tried with the default setting of monosdf, but the result was not so good as in the monosdf paper. What should I do to reproduce the result in monosdf paper?

**Comment by niujinshuchong** [comment]
Hi, could you be more specific on which dataset which scene do you try? What command do you use and what results do you get? what result do you compare to monosdf paper?

**Comment by Vilour** [comment]
> 

Hi, I tried with the Apartment data mentioned in the original monosdf repo. I ran with the following command:

ns-train monosdf --pipeline.model.sdf-field.use-grid-feature True --pipeline.model.sdf-field.geometric-init True --pipeline.model.sdf-field.inside-outside True --trainer.max-num-iterations 200000 --trainer.steps-per-eval-image 5000 --vis wandb --experiment-name monosdf-Apartment  --pipeline.model.eikonal-loss-mult 0.05  monosdf-data --data data/custom/Apartment --include_mono_prior True

This is the training log:
![image](https://user-images.githubusercontent.com/22342670/210781013-6b0fa07b-c320-4ba2-aabd-96c6a055c459.png)

I also tried the same data with original monosdf repo and the results were good, so I was not sure if I used the correct commands.

**Comment by niujinshuchong** [comment]
Hi, are you using the same network architecture in both repos? could you share your reconstruction results for comparison?

**Comment by niujinshuchong** [comment]
Hi, I think you missed `--center_crop_type no_crop` in the data loading part. Could you try with it again?

**Comment by Vilour** [comment]
Hi, I tried with no_crop and the results were much better! 
![image](https://user-images.githubusercontent.com/22342670/211179344-a61ee5db-18e1-4cbc-bb10-d70ed7b22117.png)
And here is the reconstruction results
![image](https://user-images.githubusercontent.com/22342670/211179378-889c6dd2-aa3d-4a00-82a7-cebebb6aa277.png)
It's still a little wired somehow. Anything else I can do to further improve the reconstruction results? Thank you for your excellent work!

**Comment by niujinshuchong** [comment]
Hi, great that it works. What do you mean by wired results? Some parts of the scene are never observed in the training view so the mesh is random. You could try to render depth map from extracted mesh to all training image and use tsdf fusion to get the mesh with only observed region. To improve reconstruction quality of observed region, you could try to tune the eikonal loss, depth and normal loss or use different network architecture. Using multi-gpus will also improves the results in general.

**Comment by Vilour** [comment]
Hi, this is the mesh I built from the original monosdf repo
![image](https://user-images.githubusercontent.com/22342670/211228661-2a2fc9da-a9eb-430a-94dc-d0363bbb84d3.png)
the surface is smoother comparing with the last one. And the room on the up-left corner is more like a real room. Maybe I should try more parameters to see how things rock.
