### ISSUE TITLE
How to render the training data set images?

### ISSUE THREAD

**Issue by rockywind** [autonomousvision/sdfstudio#152]
Hi, thank you for sharing the great work.
I want to render the training dataset, but I can't find any option for training dataset rendering in `ns-render -h`.

**Comment by niujinshuchong** [comment]
I think currently rendering training images is not supported but it is straightforward to implement if you use `ns-eval` and load the training images and then save the rendering results.

**Comment by rockywind** [comment]
Thanks a lot!
