### ISSUE TITLE
Dockerfile problem

### ISSUE THREAD

**Issue by aiertamundarain** [autonomousvision/sdfstudio#154]
**Describe the bug**
Dockerfile install qt5.12 , when I run sDFStudio qt 5.15 is required

**To Reproduce**
1 Build docker Image
2 Run docker image

**Expected behavior**

**Screenshots**

![screnshot](https://github.com/autonomousvision/sdfstudio/assets/48350965/da1d8289-9adf-4157-842f-7ef79d210aef)

**Additional context**

**Comment by MvWouden** [comment]
May be related to https://github.com/autonomousvision/sdfstudio/issues/129

**Comment by aiertamundarain** [comment]
Ok
