### ISSUE TITLE
how can i solve this error? Nerfstudio to sdfstudio

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#164]
![화면 캡처 2023-07-16 220421](https://github.com/autonomousvision/sdfstudio/assets/125524043/e5d56a55-47d6-41bb-9537-ae5b7198e0b7)

I would like to use sdfstudio by using my own custom dataset.i have only jpg image files But only images are not enough, so I followed the instructions in the link provided by nerfstudio at https://colmap.github.io/install.html and using the command ns-process-data {images, video} --data {DATA_PATH} --output-dir {PROCESSED_DATA_DIR}. After that, I tried to execute the sdfstudio customdata usage using the following command: python scripts/datasets/process_nerfstudio_to_sdfstudio.py --input_path nerfinput/fox --output_path outputs/fox using the folder I created. However, I encountered errors such as the one shown in the image. How can I solve this issue?

**Comment by MvWouden** [comment]
SDFStudio now supports `nerfstudio-data` as datatype in `ns-train`, no need to convert anymore.

**Comment by hanjoonwon** [comment]
ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-dtu65 sdfstudio-data --data data/sdfstudio-demo-data/dtu-scan65      
If i simply provide the folder processed by NerfStudio as the input, will it work when executing the command?

**Comment by hanjoonwon** [comment]
> SDFStudio now supports `nerfstudio-data` as datatype in `ns-train`, no need to convert anymore.

ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-dtu65 sdfstudio-data --data data/sdfstudio-demo-data/dtu-scan65      
If i simply provide the folder processed by NerfStudio as the input, will it work when executing the command?

**Comment by MvWouden** [comment]
> > SDFStudio now supports `nerfstudio-data` as datatype in `ns-train`, no need to convert anymore.
> 
> ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-dtu65 sdfstudio-data --data data/sdfstudio-demo-data/dtu-scan65 If i simply provide the folder processed by NerfStudio as the input, will it work when executing the command?

You need to replace `sdfstudio-data` with `nerfstudio-data`, so:

```shell
ns-train neus-facto ... nerfstudio-data --data path/to/data
```

**Comment by hanjoonwon** [comment]
> I tried to run it according to the command  ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-fox nerfstudio-data --data data/custom/fox2
( I copied the fox2 folder that I processed to nerfstuio under the data )
![화면 캡처 2023-07-18 140633](https://github.com/autonomousvision/sdfstudio/assets/125524043/c58040d7-49fd-452d-9b13-c81a7d5a5893)



+++Thank you for your kind reply I'm sorry to bother you, but please reply when you have time. How should I use my dataset without going through nerfstudio?? I only have a simple jpg image and I don't have the json or other depth information that sdfstudio wants, so when I use instant-ngp, the results come out only my jpg image and I could pull out the mesh model (although the mesh is not clean), but I don't know how to use sdfstudio customdata yet because i'm a beginner
