### ISSUE TITLE
assertion error  train with nerfstudio data

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#176]
I tried to run nerf studio data according to the command 
![화면 캡처 2023-07-18 140633](https://github.com/autonomousvision/sdfstudio/assets/125524043/c4ac5518-3807-4a3c-800f-1b7c11428f5c)
ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-fox nerfstudio-data --data data/custom/fox2
( I copied the fox2 folder that I processed to nerfstuio under the data )

**Comment by MvWouden** [comment]
Duplicate issue https://github.com/autonomousvision/sdfstudio/issues/176
