### ISSUE TITLE
Extracting MonoCues

### ISSUE THREAD

**Issue by LownyCGI** [autonomousvision/sdfstudio#19]
Having a trouble extracting MonoCues

It's just doesn't extract

Do i need to get camera poses beforehand?

![image](https://user-images.githubusercontent.com/36165420/211482242-dfdc5377-ceb8-4f73-8d27-40760fba3324.png)

**Comment by niujinshuchong** [comment]
Hi, I haven't tested it on the Windows system. But looks like the path is mixed with `\\` and `/`. Could you make it consistent and try again?

**Comment by niujinshuchong** [comment]
Hi, in your screenshot, the path is sometimes `C:\\` and in the end `C:/`. I am not sure whether this is the problem. I think you could try changing all of them to `\\`.

**Comment by LownyCGI** [comment]
i tried `\\` it doubled up in quantity.

**Comment by LownyCGI** [comment]
![image](https://user-images.githubusercontent.com/36165420/211877528-3cea33b7-a8f1-4856-96e2-2a71c34fa13a.png)

I reinstalled sdfstudio and put omnidata-tools on top of it. and have been running into the same problem ever since

**Comment by LownyCGI** [comment]
Solved. incorrect filenames for images. Thanks to @joeylitalien

https://github.com/autonomousvision/sdfstudio/pull/22#issuecomment-1379291842
