### ISSUE TITLE
unable to recreate the dtu65 mesh

### ISSUE THREAD

**Issue by bhavikajalli** [autonomousvision/sdfstudio#190]
Hi everyone,
I am new to sdfstudio and followed the given instructions to create the sdfstudio environment and install the required dependencies.
I want to train the given example dtu65 model and extract a mesh. to this end I tried the given commands:
`ns-download-data sdfstudio

ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-dtu65 sdfstudio-data --data data/sdfstudio-demo-data/dtu-scan65

ns-extract-mesh --load-config outputs/neus-facto-dtu65/neus-facto/2023-08-02_012705/config.yml --output-path meshes/neus_dtu65.ply --bounding-box-min -0.1 -0.1 -0.1 --bounding-box-max 0.1 0.1 0.1 --resolution 1024 --marching_cube_threshold 0.001 --create_visibility_mask True`

However, the mesh I got looks like this 
![Screenshot 2023-08-02 at 1 24 55 PM](https://github.com/autonomousvision/sdfstudio/assets/24924287/b91885ac-a323-4f15-b972-9bec0eb17fd9)

I am not sure why and what went wrong, any help would be greatly appreciated !

**Comment by niujinshuchong** [comment]
Hi, you could use this command to extract the mesh `ns-extract-mesh --load-config outputs/neus-facto-dtu65/neus-facto/XXX/config.yml --output-path meshes/neus-facto-dtu65.ply`

**Comment by bhavikajalli** [comment]
![Screenshot 2023-08-05 at 5 05 17 PM](https://github.com/autonomousvision/sdfstudio/assets/24924287/28c4cfd5-92a1-4f1b-96ad-f2484305ac23)
 It works and looks so much better. But I don't understand how. Only the name of the final file was different.

**Comment by niujinshuchong** [comment]
The main difference is the bounding box to extract the mesh, the default is -1 to 1 while you use -0.1 to 0.1 in your first command.
