### ISSUE TITLE
errror when train finished

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#191]
when I finish learning 100%, I get this error, and even if I open the mesh with the mesh lab, the file is weird
![화면 캡처 2023-07-28 183244](https://github.com/autonomousvision/sdfstudio/assets/125524043/62585c93-5f00-4cd5-be78-7956a78f35d9)
![화면 캡처 2023-07-28 191246](https://github.com/autonomousvision/sdfstudio/assets/125524043/bc5d8c4e-3cb8-4bd6-a95f-24e1ab7b4cd8)

**Comment by niujinshuchong** [comment]
Hi, how do you extract the mesh?

**Comment by hanjoonwon** [comment]
> Hi, how do you extract the mesh?

no this error occured

**Comment by niujinshuchong** [comment]
Hi, the error occurs after training finished, so you can still extract the mesh with the saved checkpoint. Please follow the instruction in readme.

**Comment by hanjoonwon** [comment]
> Hi, the error occurs after training finished, so you can still extract the mesh with the saved checkpoint. Please follow the instruction in readme.

ah second picture is mesh error, when i open extract mesh in meshlab that error occured. Mesh is coming out really weird
