### ISSUE TITLE
this error occured when training finished

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#201]
![258282769-62585c93-5f00-4cd5-be78-7956a78f35d9](https://github.com/autonomousvision/sdfstudio/assets/125524043/14d97bc5-3c94-4606-9715-204b3c7b2a5c)
![258282781-bc5d8c4e-3cb8-4bd6-a95f-24e1ab7b4cd8](https://github.com/autonomousvision/sdfstudio/assets/125524043/4b42a7c7-567f-40c6-9223-8eecb34cb980)

when I finish learning 100%, I got this error, and even if I extract mesh and open the mesh with the mesh lab, the file is weird
i trained with ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-fox nerfstudio-data

**Comment by niujinshuchong** [comment]
Hi, I didn't test the code in windows. Could you use tensorboard or wandb to visualize the training process (use `--vis wandb`)? If the log image looks good in wandb then the extracted mesh should be also good. If the error only happens at the end of training, then you could simply set a slightly large number of training iterations such as default+1 then the trained model will be saved to the disk and you can use it to extract the mesh.

**Comment by hanjoonwon** [comment]
> i trained with ns-train neus-facto --pipeline.datamanager.train-num-rays-per-batch 1000 --vis wandb nerfstudio-data --data data/custom/fox2 

https://wandb.ai/ju805604/sdfstudio/runs/zkes0blx?workspace=user-ju805604

eroor occured
![화면 캡처 2023-08-25 135104](https://github.com/autonomousvision/sdfstudio/assets/125524043/6ecaa8bb-5f60-4c22-a5f4-0a2114871b9e)
![화면 캡처 2023-08-25 135117](https://github.com/autonomousvision/sdfstudio/assets/125524043/85adbf26-88a6-498b-b7db-23e74c7a2695)

**Comment by hanjoonwon** [comment]
> Hi, I didn't test the code in windows. Could you use tensorboard or wandb to visualize the training process (use `--vis wandb`)? If the log image looks good in wandb then the extracted mesh should be also good. If the error only happens at the end of training, then you could simply set a slightly large number of training iterations such as default+1 then the trained model will be saved to the disk and you can use it to extract the mesh.

Sorry  

https://wandb.ai/ju805604/sdfstudio/workspace?workspace=user-ju805604
I changed it public
