### ISSUE TITLE
For Fisheye Support

### ISSUE THREAD

**Issue by LzqInsta** [autonomousvision/sdfstudio#204]
Hi, thanks for your great work!
I noticed that in the sdfstudio dataparser. The camera type is fixed to PERSPECTIVE.
Now I want to run sdfstudio on a set of images from fisheye camera.
I think I only need to modify line 354 in file https://github.com/autonomousvision/sdfstudio/blob/master/nerfstudio/data/dataparsers/sdfstudio_dataparser.py
from 
```python
cameras = Cameras(
            fx=fx[indices],
            fy=fy[indices],
            cx=cx[indices],
            cy=cy[indices],
            height=height,
            width=width,
            camera_to_worlds=camera_to_worlds[indices, :3, :4],
            camera_type=CameraType.PERSPECTIVE,
        )
```
to 
```python
cameras = Cameras(
            fx=fx[indices],
            fy=fy[indices],
            cx=cx[indices],
            cy=cy[indices],
            height=height,
            width=width,
            camera_to_worlds=camera_to_worlds[indices, :3, :4],
            camera_type=CameraType.FISHEYE,
            distortion_params=MY_DISTORTION_PARAMS,
        )
```
that's right? Or there exist other codes in the project that I need to modify?

**Comment by niujinshuchong** [comment]
Hi, yes, that's right.

**Comment by shwhjw** [comment]
Hi, might be a newbie question, but are the distortion_params required with a fisheye and, if so, how would I calculate them? I'm using an Insta One X2.

I realise I could probably use the equirectangular camera type but I've read the Insta's stitching isn't the best and it's better to use the 2 raw fisheye images.

**Comment by LzqInsta** [comment]
> Hi, might be a newbie question, but are the distortion_params required with a fisheye and, if so, how would I calculate them? I'm using an Insta One X2.
> 
> I realise I could probably use the equirectangular camera type but I've read the Insta's stitching isn't the best and it's better to use the 2 raw fisheye images.

In my case，I directly use the estimated distortion params by colmap.
If you want to use the 2 raw fisheye images of Insta One X2, I think the main problem is how to estimate the two fisheyes' extrinsics accurately. Since their overlapped area is really small.
