### ISSUE TITLE
what is this error??

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#205]
i trained with
![화면 캡처 2023-08-25 135104](https://github.com/autonomousvision/sdfstudio/assets/125524043/b068a21d-1456-4443-94e6-566ef120ae82)
ns-train neus-facto --pipeline.datamanager.train-num-rays-per-batch 700 --pipeline.datamanager.eval-num-rays-per-batch=32 --vis wandb nerfstudio-data --data data/custom/fox2
![화면 캡처 2023-08-25 135117](https://github.com/autonomousvision/sdfstudio/assets/125524043/bec591cb-c3d1-484a-bfc6-0f6c2a5dcc75)
 
but this error occured

**Comment by niujinshuchong** [comment]
Hi, is this error happen only on the fox dataset? Could you try other methods on the fox scene or try neus-facto with other dataset?

**Comment by hanjoonwon** [comment]
> Hi, is this error happen only on the fox dataset? Could you try other methods on the fox scene or try neus-facto with other dataset?

ns-train neus-facto --pipeline.datamanager.train-num-rays-per-batch 700 --pipeline.datamanager.eval-num-rays-per-batch=32 --vis wandsb sdfstudio-data --data/sdfstudio-demo-data/dtu-scan65

 If I use dtu data that I raise by default, no errors occur
 
Fox is a dataset created using 
ns-process-data images --data input/fox --output-dir output/fox2 of nerfstudio, but if the problem is using nerfstudio, how is it easy and convenient to generate data?

**Comment by niujinshuchong** [comment]
Hi, maybe you need to enable the background model of `neus-facto` as the background model is disabled by default.

**Comment by niujinshuchong** [comment]
Hi, you could enable it with `--pipeline.model.background-model grid `.

**Comment by hanjoonwon** [comment]
> Hi, you could enable it with `--pipeline.model.background-model grid `.

i trained with ns-train neus-facto --pipeline.datamanager.train-num-rays-per-batch 700 --pipeline.model.background-model grid --pipeline.datamanager.eval-num-rays-per-batch=32 --vis wandb nerfstudio-data --data data/custom/fox2 this 
but same error occured
 Is the dataset I processed with nerfstudio wrong?

here is my wandb https://wandb.ai/ju805604/sdfstudio?workspace=user-ju805604

![화면 캡처 2023-09-10 125255](https://github.com/autonomousvision/sdfstudio/assets/125524043/0013243f-2d05-4528-b0eb-1e90a865a50e)


![화면 캡처 2023-09-10 125239](https://github.com/autonomousvision/sdfstudio/assets/125524043/4502281f-3c54-4146-b5b5-6a96f034d118)

**Comment by hanjoonwon** [comment]
> Hi, you could enable it with `--pipeline.model.background-model grid `.

Is there something wrong with my dataset? Or is there an error in writing the nerfstudio dataset compatible
