### ISSUE TITLE
How to set the number of images extracted

### ISSUE THREAD

**Issue by 440981** [autonomousvision/sdfstudio#208]
I shot an in-room video and processed the data using the following code
```
ns-process-data video  --data /mnt/workspace/sdfstudio/data/source/Frames.m4v \
--output-dir /mnt/workspace/sdfstudio/data/goal/Frames/ --matching-method  exhaustive --num-downscales 1
```
However, only over 300 images were extracted, resulting in low data matching by Colmap
<img width="931" alt="image" src="https://github.com/autonomousvision/sdfstudio/assets/51017558/8c0d79e1-7faf-4c63-9c6b-723c4165ce7e">

**Comment by niujinshuchong** [comment]
Hi, you can try to use `--num-frames-target`.

**Comment by 440981** [comment]
> Hi, you can try to use `--num-frames-target`.

Thank you for your reply
