### ISSUE TITLE
How do I export the model I see in the viewer

### ISSUE THREAD

**Issue by 440981** [autonomousvision/sdfstudio#210]
I am now familiar with the process
1: Use the ns-extract-mesh command to export the mesh
2: Then use the scripts/texture.py script to export the mesh with texture
But the difference between the exported result and the effect seen in the viewer is very big. The performance in the viewer is very good, but the texture I exported in the end performed very poorly.

**Comment by niujinshuchong** [comment]
Hi, maybe you can refer to https://github.com/autonomousvision/sdfstudio/issues/169.
