### ISSUE TITLE
about cracks in mesh trained by neus-facto

### ISSUE THREAD

**Issue by ViokingTung** [autonomousvision/sdfstudio#211]
hi author, I used neus-facto to train a car mesh, there are some **cracks in the side and top of car**  , I tried many methods, but it still exist, can you give some suggestions? thanks. 

*command*:

```shell
ns-train neus-facto --vis viewer --viewer.websocket-port 7008 --pipeline.model.sdf-field.inside-outside False --pipeline.model.sdf-field.bias 0.3 --pipeline.model.background-model mlp --pipeline.model.sdf-field.use-diffuse-color True --pipeline.model.sdf-field.use-specular-tint True --pipeline.model.sdf-field.use-reflections True --pipeline.model.sdf-field.use-n-dot-v True --trainer.steps-per-save 80000 --trainer.steps-per-eval-batch 20000 --trainer.steps-per-eval-image 20000 --trainer.max-num-iterations 80001 sdfstudio-data --data data/sdfstudio/car-seg/
```
*mesh*:

![image](https://github.com/autonomousvision/sdfstudio/assets/17701012/8006ccf0-e5c3-4483-87f9-930d8c648493)
![image](https://github.com/autonomousvision/sdfstudio/assets/17701012/1da78f63-3ef7-42e7-9186-9234dc7c6729)

**Comment by niujinshuchong** [comment]
Hi, the cracks are probably come from the mesh simplification. Could you try to extract the mesh without mesh simplification?

**Comment by ViokingTung** [comment]
in the fact, I extract the mesh without mesh simplification, simplify-mesh is default False, do you have other ideas?
**command**
`ns-extract-mesh --load-config outputs/data-sdfstudio-car-seg/neus-facto/2023-08-29_091628/config.yml --output-path meshes-test/neus-facto-car-29_091628.ply`

**Comment by ViokingTung** [comment]
> Hi, the cracks are probably come from the mesh simplification. Could you try to extract the mesh without mesh simplification?

it seems like no relationship about mesh simplification,cause the parameter --simplify-mesh is default False. I guess it may be caused by quadric Edge Collapse Decimation , so I keep changing the parameters target_num_faces, Unfortunately the cracks become larger or smaller but does not disappeared，finally , I Increased parameters iterations when training, then extract mesh and texturing ,the cracks unbelievably disappeared, it confuses me so much.

**Comment by shenggedeqiang** [comment]
> > Hi, the cracks are probably come from the mesh simplification. Could you try to extract the mesh without mesh simplification?
> 
> it seems like no relationship about mesh simplification,cause the parameter --simplify-mesh is default False. I guess it may be caused by quadric Edge Collapse Decimation , so I keep changing the parameters target_num_faces, Unfortunately the cracks become larger or smaller but does not disappeared，finally , I Increased parameters iterations when training, then extract mesh and texturing ,the cracks unbelievably disappeared, it confuses me so much.

Can I ask you how many  iterations you used in your experiment？Will it increase lots of time？

**Comment by ViokingTung** [comment]
> > > Hi, the cracks are probably come from the mesh simplification. Could you try to extract the mesh without mesh simplification?
> > 
> > 
> > it seems like no relationship about mesh simplification,cause the parameter --simplify-mesh is default False. I guess it may be caused by quadric Edge Collapse Decimation , so I keep changing the parameters target_num_faces, Unfortunately the cracks become larger or smaller but does not disappeared，finally , I Increased parameters iterations when training, then extract mesh and texturing ,the cracks unbelievably disappeared, it confuses me so much.
> 
> Can I ask you how many iterations you used in your experiment？Will it increase lots of time？

It's been a long time, I vaguely remember about 160000 iterations , yep, as the iterations increases, the time will also increase

**Comment by shenggedeqiang** [comment]
@ViokingTung  Thanks you very much!

**Comment by basit-MT** [comment]
Hi @ViokingTung, could you share the parameters that you set for extracting mesh and texturing? The texture on the car looks great, I can't seem to get good texture on my mesh.

**Comment by ViokingTung** [comment]
> Hi @ViokingTung, could you share the parameters that you set for extracting mesh and texturing? The texture on the car looks great, I can't seem to get good texture on my mesh.

It's been so long and not sure train with below parameters.
```shell
ns-train neus-facto --vis tensorboard --viewer.websocket-port 7009 \
--pipeline.model.sdf-field.use-grid-feature True \
--pipeline.model.sdf-field.use-appearance-embedding False \
--pipeline.model.sdf-field.geometric-init True \
--pipeline.model.sdf-field.inside-outside False \
--pipeline.model.sdf-field.bias 0.3 \
--pipeline.model.sdf-field.beta-init 0.3 \
--pipeline.model.eikonal-loss-mult 0.6 \
--pipeline.model.interlevel-loss-mult 4 \
--pipeline.model.loss-coefficients.rgb-loss-coarse 4 \
--pipeline.model.loss-coefficients.rgb-loss-fine 4 \
--pipeline.model.num-samples-outside 32 \
--pipeline.model.background-model mlp \
--pipeline.model.overwrite-near-far-plane True \
--pipeline.model.near-plane 0.05 \
--pipeline.model.far-plane 4.0 \
--pipeline.model.far-plane-bg 1000 \
--pipeline.model.enable-collider True \
--pipeline.model.collider-params near_plane 2 far_plane 6 \
--pipeline.datamanager.train-num-images-to-sample-from -1 \
--pipeline.datamanager.train-num-times-to-repeat-images -1 \
--pipeline.datamanager.train-num-rays-per-batch 2048  \
--trainer.steps-per-save 160000 \
--trainer.steps-per-eval-batch 40000 \
--trainer.steps-per-eval-image 40000 \
--trainer.max-num-iterations 160001 \
sdfstudio-data --data data/sdfstudio/car3-origin/
```
