### ISSUE TITLE
Poormatches with processing DTU data

### ISSUE THREAD

**Issue by HanakoAA** [autonomousvision/sdfstudio#212]
Hello! I used the following code to process the images in the DTU dataset：
`ns-process-data images  --data data/sdfstudio-demo-data/dtu-scan65/image  --output-dir data/scan65_test --matching-method exhaustive --num-downscales 1`
and got the following output
`(  ●   ) Copying images...[08:39:56] 🎉 Done copying images.                                                             process_data_utils.py:151
[08:39:57] 🎉 Done downscaling images.                                                         process_data_utils.py:209
[08:40:01] 🎉 Done extracting COLMAP features.                                                       colmap_utils.py:531
[08:40:06] 🎉 Done matching COLMAP features.                                                         colmap_utils.py:545
[08:41:08] 🎉 Done COLMAP bundle adjustment.                                                         colmap_utils.py:567
[08:41:09] 🎉 Done refining intrinsics.                                                              colmap_utils.py:576
────────────────────────────────────────────── 🎉 🎉 🎉 All DONE 🎉 🎉 🎉 ──────────────────────────────────────────────
                                                Starting with 49 images                                                 
                                          We downsampled the images by  and 2x                                          
                                                Colmap matched 2 images                                                 
                             COLMAP only found poses for 4.08% of the images. This is low.                              
    This can be caused by a variety of reasons, such poor scene coverage, blurry images, or large exposure changes.     
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────`
May I ask why this happened?
Thank you！

**Comment by niujinshuchong** [comment]
Hi, the DTU dataset provided camera poses and you don't need to use colmap.

**Comment by HanakoAA** [comment]
Thank you for your reply，I found the problem in my Colmap version. Now I get the result:
`( ●    ) Copying images...[15:34:09] 🎉 Done copying images.                                                             process_data_utils.py:151
[15:34:10] 🎉 Done downscaling images.                                                         process_data_utils.py:209
[15:34:15] 🎉 Done extracting COLMAP features.                                                       colmap_utils.py:531
[15:34:19] 🎉 Done matching COLMAP features.                                                         colmap_utils.py:545
[15:35:17] 🎉 Done COLMAP bundle adjustment.                                                         colmap_utils.py:567
[15:35:24] 🎉 Done refining intrinsics.                                                              colmap_utils.py:576
────────────────────────────────────────────── 🎉 🎉 🎉 All DONE 🎉 🎉 🎉 ──────────────────────────────────────────────
                                                Starting with 49 images                                                 
                                          We downsampled the images by  and 2x                                          
                                                Colmap matched 49 images                                                
                                      COLAMP found poses for all images, CONGRATS!                                      
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────'

**Comment by Hmartin1978** [comment]
@HanakoAA Hello, I had the same problem as you: not only the DTU dataset but my custom dataset as well. May I ask how you solved it? 
Thank you!

**Comment by shenyehui** [comment]
> @HanakoAA Hello, I had the same problem as you: not only the DTU dataset but my custom dataset as well. May I ask how you solved it? Thank you!

May I ask if you have solved this problem? I had the same problem.

**Comment by HanakoAA** [comment]
> > @HanakoAA Hello, I had the same problem as you: not only the DTU dataset but my custom dataset as well. May I ask how you solved it? Thank you!
> 
> May I ask if you have solved this problem? I had the same problem.

Hello! I solved the problem by changing my Colmap version from 3.7 to 3.8. You can have a try. Sorry for replying so late.

**Comment by HanakoAA** [comment]
> @HanakoAA Hello, I had the same problem as you: not only the DTU dataset but my custom dataset as well. May I ask how you solved it? Thank you!

Hello! I solved the problem by changing my Colmap version from 3.7 to 3.8. You can have a try. Sorry for replying so late.
