### ISSUE TITLE
failed on custom dataset

### ISSUE THREAD

**Issue by blacksino** [autonomousvision/sdfstudio#216]
hello. Just follow the guide and train on my custom dataset,the results are quite strange.

<img width="869" alt="截屏2023-09-08 14 58 36" src="https://github.com/autonomousvision/sdfstudio/assets/44363764/c429d5c0-1987-43ef-a86b-112911f3c558">

nothing but floaters.

here are my data:
<img width="719" alt="截屏2023-09-08 15 01 58" src="https://github.com/autonomousvision/sdfstudio/assets/44363764/03f23a1b-ca5f-4043-bdec-2fdd30759a8a">

command:
ns-train neus-facto --machine.num-gpus 2 --experiment-name boy --pipeline.model.sdf-field.inside-outside False --nerfstudio-data --data /workspace/bot_2

**Comment by niujinshuchong** [comment]
Hi, your data has complex background while the background model is disabled by default in deus-facto, Could you try to enable it with `--pipeline.model.background-model grid ` and try again?

**Comment by blacksino** [comment]
much better if I enable background model,great work! BTW,what is background model?
