### ISSUE TITLE
how to remove floaters

### ISSUE THREAD

**Issue by blacksino** [autonomousvision/sdfstudio#222]
hello, how could I remove those floaters,my training images are masked, and I have added  mask for sdfstudio dataparser.(only sample nonzero area).
And I still got those floaters. What should I do,thansk!
<img width="905" alt="截屏2023-09-20 17 12 03" src="https://github.com/autonomousvision/sdfstudio/assets/44363764/4b696237-d926-4912-8d51-b79b83bf1463">

**Comment by blacksino** [comment]
and I have also set fg_mask_multi as 0.3 and I just found that  there is no fg loss in bakedangelo which means I can not impose fg_loss on Bakesdf based method?

**Comment by z-x-j** [comment]
"How did you solve this problem?" thank you
