### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#223]
i trained with ns-train neus-facto --pipeline.datamanager.train-num-rays-per-batch 700 --pipeline.model.background-model grid --pipeline.datamanager.eval-num-rays-per-batch=32 --vis wandb nerfstudio-data --data data/custom/fox2 this
![화면 캡처 2023-09-10 125239](https://github.com/autonomousvision/sdfstudio/assets/125524043/f93ea757-1804-4099-9a06-e871fa0b27cf)
![화면 캡처 2023-09-10 125255](https://github.com/autonomousvision/sdfstudio/assets/125524043/000215f7-22ee-4968-976a-3466c19cccda)

but error occured
Is the dataset I processed with nerfstudio wrong?

here is my wandb https://wandb.ai/ju805604/sdfstudio?workspace=user-ju805604

**Comment by HungNgoCT** [comment]
Same problem
