### ISSUE TITLE
Visualize trained model with viewer

### ISSUE THREAD

**Issue by KookHoiKim** [autonomousvision/sdfstudio#23]
Hi, thank you for great work! 

I'm working with your code and I wonder how to visualize trained model with viewer. 

I read that just resume training with option `--viewer.start-train False` . 

However, in the code when load the checkpoint, I didn't find that code loads the configuration file of checkpoint. 

1. So I wonder that it doesn't affect to the visualization result without loading configuration of loaded checkpoint? 
2. When I resume training with checkpoint, also does it not affect to further training? 

Thanks :)

**Comment by niujinshuchong** [comment]
Hi,

If you use `--viewer.start-train False`, then it won't start training.

1. It will only load the checkpoint. The config is specified in the training command. So yes, it doesn't affect the visualization result without loading the configuration of the loaded checkpoint. You need to use the same command as the trained model you want to resume but add `--trainer.load-dir`. (You can also use `--trainer.load-config` to load the config, but in this case, all other commands will be overwritten with the value in the config file, so it won't load the checkpoint even if it's specified in the command. This is unexpected behavior and should be fixed later).
2. When you resume training with a checkpoint, it will start training from the state saved in the checkpoint.
