### ISSUE TITLE
Texturing mesh

### ISSUE THREAD

**Issue by MaroonAmor** [autonomousvision/sdfstudio#24]
Hi,

Thanks for sharing the great work!

I spotted that we have [`scripts/texture.py`](https://github.com/autonomousvision/sdfstudio/blob/3b7670e9db41a0a7b3b3c93eacc18ce39ba3ba61/scripts/texture.py) from Nerfstudio.

Is texturing mesh ready to use here? Could you give some directions on how to use it in this repo?

Thanks again.

**Comment by niujinshuchong** [comment]
Yes, you can use it like this:
```bash
python scripts/texture.py --load-config outputs/neus-facto-dtu65/neus-facto/XXX/config.yml --input-mesh-filename ./meshes/test.ply --output-dir ./textures --target_num_faces 50000
```
after you trained the model and extracted the mesh following our readme. (You need to use the latest code)

**Comment by MaroonAmor** [comment]
@niujinshuchong Wow! Perfect! I will give it a try! Thanks a lot. :+1:

**Comment by basit-MT** [comment]
@niujinshuchong It takes too long to generate texture for high resolution meshes. Is there a way to make it faster?
