### ISSUE TITLE
Rendering at extremely low resolution during training 

### ISSUE THREAD

**Issue by ywwynm** [autonomousvision/sdfstudio#241]
I train the neus-facto model using the default command as presented in the README:

`ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-dtu65 sdfstudio-data --data data/sdfstudio-demo-data/dtu-scan65
`
Then I launch the webviewer in Firefox browser, and find the rendering resolution is extremely low (10x18 pixels) that I literately cannot see any result.

![微信图片_20231028211926](https://github.com/autonomousvision/sdfstudio/assets/7836368/bb4a1fdc-8ab5-452a-996e-1492b50eef7a)

**Comment by LevinJ** [comment]
I encountered exactly the same problems after installing sdfstudio and  issuing the above tutorial commend. Does anyone know how to get around this?

**Comment by niujinshuchong** [comment]
Hi, maybe the training is too slow for your machine so it adapts to render very low res images. You can adjust here 
![image](https://github.com/autonomousvision/sdfstudio/assets/13434986/92a03f35-b6f8-47d6-bbe9-cbe376e78d51)
 to choose resolutions.

**Comment by LevinJ** [comment]
yeah, maybe my 3090 is too slow. Adjusting the above config doesn't help much. I end up switching to wand for monitoring. Thanks a lot for the advice.

**Comment by ywwynm** [comment]
Thanks for the advice. My device is also 3090 (3*3090 actually). So training sdfstudio requires much more computational resources than nerfstudio.
