### ISSUE TITLE
Facing foward scene supported

### ISSUE THREAD

**Issue by blacksino** [autonomousvision/sdfstudio#243]
Can the scenario of facing forward be supported?

**Comment by niujinshuchong** [comment]
Hi, we didn't test on forward facing scene like LLFF. But maybe DTU is something similar to forward facing scene which works in SDFStudio. So I guess if you prepare your data in our data format and normalise it such that the main object is within -1 to 1, it should work.

**Comment by blacksino** [comment]
thanks
