### ISSUE TITLE
Strange result of Neus on Mipnerf360 bicycle

### ISSUE THREAD

**Issue by EugeneLiu01** [autonomousvision/sdfstudio#245]
I've try to run Neus on Mipnerf360 bicycle. The data i download from [here](https://drive.google.com/file/d/1sgKr0ZO7BQC0FYinAnRSxobIWNucAST5/view?usp=sharing) is attached with `transform.json`.
The cmd is 
```
ns-train neus --pipeline.model.sdf-field.use-grid-feature True \
--pipeline.model.sdf-field.hidden-dim 256 \
--pipeline.model.sdf-field.num-layers 2 \
--pipeline.model.sdf-field.num-layers-color 2 \
--pipeline.model.sdf-field.use-appearance-embedding False \
--pipeline.model.sdf-field.geometric-init True \
--pipeline.model.sdf-field.inside-outside False \
--pipeline.model.sdf-field.bias 0.5 \
--pipeline.model.sdf-field.beta-init 0.3 \
--trainer.steps-per-eval-image 5000 \
--pipeline.datamanager.train-num-rays-per-batch 2048 \
--pipeline.model.background-model none \
--vis wandb --experiment-name bicycle-test mipnerf360-data \
--data data/nerfstudio-data-mipnerf360/bicycle
```
And the result at 35k iters
depth map
![depth_35000_e001e34a0d685c72c4f2](https://github.com/autonomousvision/sdfstudio/assets/68947207/0911074d-3d73-449d-b53f-8751416e7931)
rgb
![img_35000_7a74cb03c7a6b5ef5772](https://github.com/autonomousvision/sdfstudio/assets/68947207/d36e4317-decb-405b-a414-e64cdf003153)

I suspect that the bbox is not suitable set, but idk how can i do it.

**Comment by niujinshuchong** [comment]
Hi, given the complex background of this scene, you should enable background model.

**Comment by EugeneLiu01** [comment]
It works! Thank you so much!
