### ISSUE TITLE
Poor pose match with custom dataset & DTU dataset

### ISSUE THREAD

**Issue by Hmartin1978** [autonomousvision/sdfstudio#250]
Hello! Thank you very much for great works!!!
I'm having a problem now: when I want to process custom dataset(i.e. get nerfstudio data format from the _**ns-process-data**_), the result shows that the matched poses are very low; and I try to do same thing to DTU dataset which has the same problem.
The code:
`ns-process-data images --data data/dtu/scan65/image/ --output-dir data/...`
![colmap](https://github.com/autonomousvision/sdfstudio/assets/115940971/88eb253e-c70f-45ef-92ef-2add376498e2)
I also tried use _--matching-method exhaustive_ but nothing has changed.

One strange: the first time I used this method with custom dataset it worked, then next day I used the same command again but it failed, and it's not working at all now, very confusing!

Could you please support some solutions? Thank you!!!

**Comment by niujinshuchong** [comment]
Hi, the DTU dataset provides GT poses. Scan65 is textless which is difficult for colmap to find correspondences. Maybe you can try to use T&T dataset which I tried before and it works out of box with colmap (if you just want to check if colmap is working properly).

**Comment by Hmartin1978** [comment]
OK, thank you for the reply
