### ISSUE TITLE
Train NeuS on indoor scene 

### ISSUE THREAD

**Issue by Antoine251** [autonomousvision/sdfstudio#258]
Hi,

I want to train SDF-based models on indoor scenes (with Replica dataset for now), so I started with NeuS to have a baseline. The RGB reconstruction is descent (~23 dB after a few hoors of training) but once I export the mesh from the trained model, the mesh is catastrophic. There is basically nothing, only kind of bubbles of points. I tried tuning the bias parameter as I read that it can have some impact but with no sucess. 
Is my issue something that somebody had already seen ? Is there some other parameters I should look up to ?

Thanks a lot

**Comment by niujinshuchong** [comment]
Hi, NeuS's reconstruction on indoor scene won't be good, maybe you could enable monocular depth and normal loss. You can also refer to https://github.com/autonomousvision/monosdf for more details.

**Comment by Antoine251** [comment]
Great I already got some better results with monosdf! Thanks! NeuS was not powerful enough I guess... With monosdf, what are the metrics and loss values that I could hope for with an indoor scene ? (like the ScanNet dataset you used) Knowing that I am trying not to use the depth and normal estimations, so I am using with VolSDF I guess.
