### ISSUE TITLE
inside_outside parameter not working for indoor scene ?

### ISSUE THREAD

**Issue by Antoine251** [autonomousvision/sdfstudio#260]
Hi ! 

I have an interesting issue. I am training mono-sdf on an indoor scene (Replica dataset). The training goes well with final loss and metrics as such:
- beta: 0.005257398
- depth_loss: 0.1531072
- eikonal_loss: 0.02886924
- normal_loss: 0.07076976
- psnr: 20.14746
- rgb_loss: 0.05865213

But when exporting the point cloud, i have nothing, there is no mesh in the extracted file. So I computed the SDF value in x-y planes at different z (kind of a visualization of what the marching cube algo is working on) and surprise.....

![Screenshot from 2023-12-14 11-50-08](https://github.com/autonomousvision/sdfstudio/assets/80030236/2a225e04-da6e-4b5f-9560-f5c320696be9)

We see that the interior walls are indeed detected and that the sdf value is close to 0 on the walls. But in the interior and the exterior, the sdf value is positive!! which explains why the mesh is not well extracted... 
I thought that by setting inside_outside=True , the sdf would be negative in the exterior of the building but it's not the case. Do you have any idea where does this comes from ? 

PS: When extracting the mesh, if I set isosurface_threshold to 0.02 I get a much better result but I would like to keep it at 0 as it is a geometric constraint...)

**Comment by niujinshuchong** [comment]
Why there is grid like artifacts in your visualization?

**Comment by Antoine251** [comment]
I don't know, that's also an issue with the sdf, I think the grid structure is kind of a local minima to have a gradient of 1 without having a real slope.

**Comment by Antoine251** [comment]
Okay the problem was in my dataparser I didn't load the depth correctly... Sorry for the inconvenience, I close the issue.
