### ISSUE TITLE
Neuralangelo vs Bakedangelo: differences

### ISSUE THREAD

**Issue by davidceka** [autonomousvision/sdfstudio#261]
Hi, I'm working on some surface reconstruction tasks and I've wondered what is the difference between neuralangelo and bakedangelo, if any of you could sum it up in some points. I also haven't found any paper about bakedangelo so far, only neuralangelo and bakedsdf individually.

Thanks in advance.

**Comment by niujinshuchong** [comment]
Hi, `bakedangelo` has a better background modeling where we use proposal networks for both SDF and the background NeRF model. And since we are using proposal networks, the sampling is more efficient and can be trained with only a singel GPU instead of 8 GPUs in `neuralangelo`.

**Comment by davidceka** [comment]
> Hi, `bakedangelo` has a better background modeling where we use proposal networks for both SDF and the background NeRF model. And since we are using proposal networks, the sampling is more efficient and can be trained with only a singel GPU instead of 8 GPUs in `neuralangelo`.

Thanks for answering. 

Is there any paper or resource for bakedangelo i can read more closely and which I can quote? I'm planning on writing a thesis work and I would like to cite all the resources I can. I would like to justify the usage of bakedangelo over typical neuralangelo watching also various metrics that I'm evaluating.

**Comment by niujinshuchong** [comment]
Hi, we don't have a paper for sdfstudio. You can check the code for details. You can simply cite sdfstudio :)

**Comment by davidceka** [comment]
Thanks for the help then, I most definitely will!
