### ISSUE TITLE
training is too slow

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#267]
i trained with ns-train bakedangelo --pipeline.datamanager.train-num-rays-per-batch 700 --pipeline.model.background-model grid --pipeline.datamanager.eval-num-rays-per-batch=32 --experiment-name sdfscan nerfstudio-data --data C:\deeplearning\nerfstudio\output\scan2  
But the training is going too slow, so I want to ask what parts to adjust to make the training better
my gpu is rtx 2060, vram 6gb
![image](https://github.com/autonomousvision/sdfstudio/assets/125524043/0184a8db-2fcf-413c-a455-16f2c6d49d6d)

**Comment by JLee2022** [comment]
can you fix it ?

**Comment by JLee2022** [comment]
have you fixed it? I have the same problem.
