### ISSUE TITLE
Nerfstudio-data vs sdfstudio-data

### ISSUE THREAD

**Issue by davidceka** [autonomousvision/sdfstudio#270]
Hi, I'm in the process of training some models and I was wondering: what's the point of converting my nerfstudio-data to sdfstudio-data if both bakedangelo and nerfacto can use as input the nerfstudio-data format? Are there specific models that can't process nerfstudio-data?

**Comment by niujinshuchong** [comment]
Hi, you can use any data format for training. The reason why we have sdfstudio-data is because we also support monocular depth and normal since they are helpful for some scenarios.
