### ISSUE TITLE
DTU demo scene is flipped upside down

### ISSUE THREAD

**Issue by pschroeppel** [autonomousvision/sdfstudio#28]
Hi,
I tried to reproduce the "Train your first model" steps in the README, i.e. I executed the following command:
```bash
ns-train neus-facto --pipeline.model.sdf-field.inside-outside False --vis viewer --experiment-name neus-facto-dtu65 sdfstudio-data --data data/sdfstudio-demo-data/dtu-scan65
```
However, the input images are loaded upside down. Hence I could not reproduce the viewer state that is shown in the README image <https://github.com/autonomousvision/sdfstudio/blob/master/media/viewer_screenshot.png>. As the viewer does not allow a full 180 degree flip, it was not possible to view the scene in the correct orientation.

I could fix the problem by setting `auto_orient` in the file `nerfstudio/data/dataparsers/sdfstudio_dataparser.py` to `True`. However, I'm not sure if this is a bug or intended, hence I opened this issue.

**Comment by niujinshuchong** [comment]
Hi, I think that's not the bug. It's because DTU dataset has different orientations with viewer and you can set auto-orient to True to the end of your training command `--auto-orient True`. We set the default value of auto-orient to False to make it consistent with pervious work (e.g. volsdf and monosdf).

**Comment by pschroeppel** [comment]
Ok, I was not aware that this is available as a command line parameter. Thanks :)

**Comment by hanjoonwon** [comment]
> Hi, I think that's not the bug. It's because DTU dataset has different orientations with viewer and you can set auto-orient to True to the end of your training command `--auto-orient True`. We set the default value of auto-orient to False to make it consistent with pervious work (e.g. volsdf and monosdf).

![image](https://github.com/autonomousvision/sdfstudio/assets/125524043/b502edd6-7164-4eee-89be-a61d4c9abaeb)
when i try to use auto orient, got this error
ns-train neus-facto --pipeline.datamanager.train-num-rays-per-batch 1024   --pipeline.model.sdf-field.use-grid-feature False  --pipeline.model.mono-depth-loss-mult 0.5 --pipeline.model.mono-normal-loss-mult 0.05   --vis wandb --pipeline.model.sdf-field.inside-outside False --pipeline.model.background-model grid --trainer.steps_per_save 5000  --trainer.steps-per-eval-image 5000  --trainer.max-num-iterations 300000 --experiment-name hasmaskmodifyvidbat2 sdfstudio-data --data /workspace/processdata/hasmaskmodifyvidbat --auto_orient True
