### ISSUE TITLE
how to get only object not background

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#281]
i want to get object only. not background
Are there any other options besides adding a foreground mask?

**Comment by niujinshuchong** [comment]
Hi, the easier way is to train the model with background and crop or extract the ROI after training.

**Comment by hanjoonwon** [comment]
> Hi, the easier way is to train the model with background and crop or extract the ROI after training.

than you:)  But I don't know how to do it, can you recommend a way to cleanly remove only the mesh part I want?
Currently, when I remove it from meshlab, the bounds that touch the object I want are lowered, leaving the object open and empty.
