### ISSUE TITLE
Is it possible to print a  dimensions of the extracted mesh 

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#283]
thank you for your work

I am a mechanical engineering student and new to this area, so I don't know much about it yet.
 Currently, we are working on meshing the images taken by the 3d scanner hardware we made with sdfstudio and printing them with a 3d printer.(Of course, we're still not reconstructing our objects properly, but...)
 
I was wondering if it is possible to print the dimensions of the extracted mesh (even if it is from a previous train).
I'm not sure what part of the current docker container needs to be modified to add the ability to print dimensions.

Finally, I was wondering if I could extract only the parts of the mesh I wanted. Like the viewer of instant-ngp, I can adjust the bounding box to extract only the part I want.
<img width="429" alt="image" src="https://github.com/autonomousvision/sdfstudio/assets/125524043/4852024c-1113-4f47-9779-0525fc4164eb">

Currently, my results overlap the object I want and most of the pedestal, so I can't get just the object I want.

**Comment by niujinshuchong** [comment]
If you know the bbox for the object, you can just specify it during mesh extraction like `--bounding-box-min -2.0 -2.0 -2.0 --bounding-box-max 2.0 2.0 2.0 `

**Comment by hanjoonwon** [comment]
> If you know the bbox for the object, you can just specify it during mesh extraction like `--bounding-box-min -2.0 -2.0 -2.0 --bounding-box-max 2.0 2.0 2.0 `

@niujinshuchong  thanks   how do i know bbox??
