### ISSUE TITLE
is monosdf and neuralangelo inherently slow?

### ISSUE THREAD

**Issue by hanjoonwon** [autonomousvision/sdfstudio#284]
![image](https://github.com/autonomousvision/sdfstudio/assets/125524043/368fb166-d104-465a-b1dd-b78aee27c673)
When I use neus,neuralangelo,monosdf,etc except neus-facto,the train iter is quite slow as shown below. Is this a normal result?
My graphic card is rtx 2060 vram 6gb

i trained with
ns-train neus --pipeline.datamanager.train-num-rays-per-batch 1024 
 --pipeline.model.sdf-field.bias 0.3  --pipeline.model.sdf-field.use-grid-feature False
   --pipeline.model.background-model mlp  --pipeline.model.mono-depth-loss-mult 0.1 
   --pipeline.model.mono-normal-loss-mult 0.05   --vis wandb 
   --pipeline.model.sdf-field.inside-outside False  --trainer.steps_per_save 5000  
   --trainer.steps-per-eval-image 5000  --trainer.max-num-iterations 300000
    --experiment-name newwvidbat sdfstudio-data --data /workspace/processdata/vidbat

**Comment by niujinshuchong** [comment]
Hi, it depends on the point sampling and the network architecture. NeuS is slower than neus-facto since more points are sampled on the ray and the default nextowrk architecture is different.

**Comment by hanjoonwon** [comment]
> Hi, it depends on the point sampling and the network architecture. NeuS is slower than neus-facto since more points are sampled on the ray and the default nextowrk architecture is different.

@niujinshuchong  in case of neuralangelo  iter time 1 miniute..  that is because of my gpu??  I use rtx 2060
