### ISSUE TITLE
Support dynamic scenes?

### ISSUE THREAD

**Issue by chenerg** [autonomousvision/sdfstudio#3]
Do you plan to support dynamic scenes?

**Comment by niujinshuchong** [comment]
Hi, we don't have a plan for supporting dynamic scenes but it would be great to have that. Could you provide some references?

**Comment by chenerg** [comment]
There are dynamic nerf methods such as D-Nerf, Nerfies, and others. I think these methods can be applied to SDF methods. As for dynamic SDF, I only know about Neus2.

**Comment by niujinshuchong** [comment]
Thanks for the references.
