### ISSUE TITLE
Missing `triplane` implementation

### ISSUE THREAD

**Issue by wsunid** [autonomousvision/sdfstudio#36]
Hi,

First, thanks for opening source this code. It's super useful!

Here I report the bug I found. I'm not sure if I mistake something. So I would like to confirm it here. Thanks! 

I can't use the `triplane` as the sdf field whereas Document said triplane feature is supported.  

Specifically,  it reports the error when I run CMD: `ns-train neus --pipeline.model.sdf-field.use-grid-feature True  --pipeline.model.sdf-field.encoding-type tri-plane sdfstudio-data --data data/sdfstudio-demo-data/dtu-scan65/`

![image](https://user-images.githubusercontent.com/42977650/216719536-ece35987-ee4c-4aa2-9195-97ec7261a1e0.png)

I checked the code. Seems the code didn't implement the triplane if I understand correctly. 

https://github.com/autonomousvision/sdfstudio/blob/58bd9aca22650ebc629481db11c7173f40400f87/nerfstudio/field_components/encodings.py#L415

Did I miss something in Document?

Thanks,
Weiwei.

**Comment by niujinshuchong** [comment]
Hi, currently `tensorf_vm` is the triplane represenation since we skip the line feature in `tensorf_vm` here https://github.com/autonomousvision/sdfstudio/blob/master/nerfstudio/field_components/encodings.py#L528-L529. Will update it later.

**Comment by wsunid** [comment]
okay, I see. Thanks for the reply!
