### ISSUE TITLE
Monocular cues importance

### ISSUE THREAD

**Issue by ducha-aiki** [autonomousvision/sdfstudio#38]
Hi,

Thanks for the great project! I have a rather stupid question - have anyone compared influence of difference monodepth/normals methods?   Like https://github.com/baegwangbin/IronDepth ? 
Or are the omnidata ones the best? 

--
Best, Dmytro

**Comment by niujinshuchong** [comment]
Hi, we have a simple comparison of using different monocular depth and normal methods on one of the Replica scene. Please check table 9 in the paper https://arxiv.org/pdf/2206.00665.pdf. Omnidata model is the best among the models we tested but of course other models might performs better on different scenes.

**Comment by ducha-aiki** [comment]
Thank you!

For those who stumble upon the issue, here is that Table:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/4803565/217765737-f508f897-da49-4759-97e4-24fbf1c38e64.png">

**Comment by basit-MT** [comment]
Hi @niujinshuchong, I see that depth from monocular_cues.py follows some scale, what is that scale?

Moroever, if I want to try let's say Depth-anything method for monocular cues, what scale should I apply for a custom scene?  how should "--pipeline.model.mono-depth-loss-mult" change for different scales?
