### ISSUE TITLE
How to improve training efficiency

### ISSUE THREAD

**Issue by krahets** [autonomousvision/sdfstudio#40]
Hi @niujinshuchong ! I noticed that the training speed of `neus-facto` is ~3 times slower than `nerfacto`.

I have tested the time per iteration

```
# nerfstudio
loss_time = 15.6 ms
backward_time = 6.8 ms
total = 22.5 ms
```

```
# sdfstudio
loss_time = 30.2 ms
backward_time = 44.0 ms
total = 74.3 ms
```

I'm wondering about your insights or suggestions to improve the training efficiency. Thanks!

**Comment by niujinshuchong** [comment]
Hi, I think it's because `neus-facto` use a larger MLP (dim=256 with 2 hidden layer vs dim=64 with 1 hidden layer) and `neus-facto` need to compute the gradient of SDF and use it as input to color network and eikonal loss. We use a larger mlp because we found it results in more smooth surface on the DTU dataset.

**Comment by krahets** [comment]
Thanks for the great guidance!

I reduced the size of the MLP and it speed up ~1.5 times with a slight degradation in mesh accuracy.

**Comment by krahets** [comment]
One more thing, please. I found the learning rate is set as 5e-4 in sdfstudio. I increased the lr by 2~5 times and didn't find degradation. I'm wondering why to use such a small learning rate.

Thanks!

**Comment by niujinshuchong** [comment]
Hi, a small learning rate should be used for pure MLP and small lr also works with feature grids so I make it default such that we don't need to change lr when we switch different representations. Ideally we should set different lrs for different cases or even use different lr for the feature grid and mlp parts which is useful in some cases when we did experiments with MonoSDF repo but I don't have detailed comparison.

**Comment by krahets** [comment]
Thanks for the clear description! I agree that we can set the default learning rates differently according to the field representation.

I think it is safe to change the default lr only by `--pipeline.model.sdf-field.use-grid-feature`. If you agree, I'll create a related PR after taking sufficient experiments.

**Comment by niujinshuchong** [comment]
Yes, I think adding an option to set lr only for feature grids would be great. If the lr of feature grid is not specified in command line then it should be the same as the network.
