### ISSUE TITLE
Even if I set the same parameters and dataset, the mesh of sdfstudio monosdf pipline is different from original monosdf mesh.

### ISSUE THREAD

**Issue by BingHanOfUESTC** [autonomousvision/sdfstudio#45]
Hi, dear author.
I trained the sdfstudio monosdf pipline using the same dataset and the same parameter with the original monosdf,  while meshes are different. The floor of mesh extracted from sdfsutdio monosdf pipline is raised. However, the floor of mesh extracted from original monosdf is smooth and flat. Have you had any similar problems when compared to the original monosdf results?
My parameters are:
ns-train monosdf --pipeline.model.sdf-field.inside-outside True --pipeline.model.eikonal-loss-mult 0.05 --pipeline.model.mono-depth-loss-mult 0.1 --pipeline.model.mono-normal-loss-mult 0.05 --pipeline.model.sdf-field.use-grid-feature True --pipeline.model.sdf-field.bias 0.9 --pipeline.model.sdf-field.divide-factor 1.5 --trainer.steps-per-save 50000 --trainer.max-num-iterations 200000 --vis viewer --experiment-name monosdf_cyberlab_train3 sdfstudio-data --data xx/scan1 --include_mono_prior True 

Thanks!

**Comment by niujinshuchong** [comment]
Hi, which dataset did you try? Could you share a comparison of the reconstructed results?

**Comment by BingHanOfUESTC** [comment]
Hi, the question above comes from my own dataset. For ease of comparison, I tried on your tnt dataset, I trained on tnt scan1. But I can't get surface on trained model. Could you please share the training parameter settings of tnt dataset?
My trained parameters settings are:
CUDA_VISIBLE_DEVICES=0 ns-train monosdf --pipeline.model.sdf-field.inside-outside True --pipeline.model.eikonal-loss-mult 0.1 --pipeline.model.mono-depth-loss-mult 0.05 --pipeline.model.mono-normal-loss-mult 0.01 --pipeline.model.sdf-field.use-grid-feature True --pipeline.model.sdf-field.bias 1 --pipeline.model.sdf-field.divide-factor 1.5 --pipeline.model.sdf-field.num-layers 4 --pipeline.model.sdf-field.num-layers-color 2 --trainer.steps-per-save 5000 --trainer.max-num-iterations 100000 --vis viewer --viewer.websocket-port 7006 --experiment-name monosdf_tnt_scan1_v1 monosdf-data --center-crop-type center_crop_for_tnt --data tnt/scan1/ --include_mono_prior True

**Comment by niujinshuchong** [comment]
Hi, could you try 
```bash
ns-train monosdf --pipeline.model.sdf-field.use-grid-feature True --pipeline.model.sdf-field.use-appearance-embedding True --pipeline.model.sdf-field.geometric-init True --pipeline.model.sdf-field.inside-outside True  --pipeline.model.sdf-field.bias 0.8 --pipeline.model.sdf-field.beta-init 0.1 --pipeline.datamanager.train-num-images-to-sample-from 1 --pipeline.datamanager.train-num-times-to-repeat-images 0 --trainer.steps-per-eval-image 5000 --pipeline.model.background-model none --vis wandb --experiment-name monosdf-tnt1 --pipeline.model.mono-depth-loss-mult 0.1 --pipeline.model.mono-normal-loss-mult 0.05 --pipeline.model.eikonal-loss-mult 0.1 --pipeline.datamanager.train-num-rays-per-batch 2048 sdfstudio-data --data data/tanks-and-temple/scan1 --include_mono_prior True
```

**Comment by BingHanOfUESTC** [comment]
I'm sorry I didn't get good results with this set of parameters. And I find it can't match the parameters in original monosdf code. Could you please share some good results parameters in TNT dataset in this projects? 
Thanks!

**Comment by BingHanOfUESTC** [comment]
Thanks.
Your parameters helped me solve my problem on my own dataset. I think '--pipeline.datamanager.train-num-images-to-sample-from 1 --pipeline.datamanager.train-num-times-to-repeat-images 0' are critical. I guess if the rays are randomly sampled from different images, the scales of depth obtained from omonidata are different, especially in large areas of weak texture such as the floor.
And I tried your parameters in tnt scan1. However, minimum overflow occurred during training. I guess "--pipeline.model.sdf-field.use-appearance-embedding True" is the culprit. I'm continuing to experiment sdfstudio on tnt dataset.

**Comment by BingHanOfUESTC** [comment]
The minimum overflow while training tnt dataset mentioned above is
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.1385
VanillaPipeline.get_train_loss_dict: 0.0723
Trainer.eval_iteration: 0.0000
Traceback (most recent call last):
  File "sdfstudio/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "sdfstudio-master/scripts/train.py", line 248, in entrypoint
    main(
  File "sdfstudio-master/scripts/train.py", line 234, in main
    launch(
  File "sdfstudio-master/scripts/train.py", line 173, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "sdfstudio-master/scripts/train.py", line 88, in train_loop
    trainer.train()
  File "sdfstudio-master/nerfstudio/engine/trainer.py", line 174, in train
    self.eval_iteration(step)
  File "sdfstudio-master/nerfstudio/utils/decorators.py", line 70, in wrapper
    ret = func(self, *args, **kwargs)
  File "sdfstudio-master/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "sdfstudio-master/nerfstudio/engine/trainer.py", line 347, in eval_iteration
    metrics_dict, images_dict = self.pipeline.get_eval_image_metrics_and_images(step=step)
  File "sdfstudio-master/nerfstudio/utils/profiler.py", line 43, in wrapper
    ret = func(*args, **kwargs)
  File "sdfstudio-master/nerfstudio/pipelines/base_pipeline.py", line 311, in get_eval_image_metrics_and_images
    metrics_dict, images_dict = self.model.get_image_metrics_and_images(outputs, batch)
  File "sdfstudio-master/nerfstudio/models/base_surface_model.py", line 440, in get_image_metrics_and_images
    acc = colormaps.apply_colormap(outputs["accumulation"])
  File "sdfstudio-master/nerfstudio/utils/colormaps.py", line 42, in apply_colormap
    assert image_long_min >= 0, f"the min value is {image_long_min}"
AssertionError: the min value is -9223372036854775808

I tried many times with different setting with your parameter suggestion. Could you please analysis this error?

**Comment by BingHanOfUESTC** [comment]
The minimum overflow while training tnt dataset mentioned above is
Printing profiling stats, from longest to shortest duration in seconds
Trainer.train_iteration: 0.1385
VanillaPipeline.get_train_loss_dict: 0.0723
Trainer.eval_iteration: 0.0000
Traceback (most recent call last):
File "sdfstudio/bin/ns-train", line 8, in
sys.exit(entrypoint())
File "sdfstudio-master/scripts/train.py", line 248, in entrypoint
main(
File "sdfstudio-master/scripts/train.py", line 234, in main
launch(
File "sdfstudio-master/scripts/train.py", line 173, in launch
main_func(local_rank=0, world_size=world_size, config=config)
File "sdfstudio-master/scripts/train.py", line 88, in train_loop
trainer.train()
File "sdfstudio-master/nerfstudio/engine/trainer.py", line 174, in train
self.eval_iteration(step)
File "sdfstudio-master/nerfstudio/utils/decorators.py", line 70, in wrapper
ret = func(self, *args, **kwargs)
File "sdfstudio-master/nerfstudio/utils/profiler.py", line 43, in wrapper
ret = func(*args, **kwargs)
File "sdfstudio-master/nerfstudio/engine/trainer.py", line 347, in eval_iteration
metrics_dict, images_dict = self.pipeline.get_eval_image_metrics_and_images(step=step)
File "sdfstudio-master/nerfstudio/utils/profiler.py", line 43, in wrapper
ret = func(*args, **kwargs)
File "sdfstudio-master/nerfstudio/pipelines/base_pipeline.py", line 311, in get_eval_image_metrics_and_images
metrics_dict, images_dict = self.model.get_image_metrics_and_images(outputs, batch)
File "sdfstudio-master/nerfstudio/models/base_surface_model.py", line 440, in get_image_metrics_and_images
acc = colormaps.apply_colormap(outputs["accumulation"])
File "sdfstudio-master/nerfstudio/utils/colormaps.py", line 42, in apply_colormap
assert image_long_min >= 0, f"the min value is {image_long_min}"
AssertionError: the min value is -9223372036854775808

I tried many times with different setting. Could you please analysis this error?

**Comment by niujinshuchong** [comment]
Hi, which method give this error? Could you share the full command that you used to train the model?

**Comment by BingHanOfUESTC** [comment]
Monosdf method on highres_TNT and tnt dataset. Full command is
CUDA_VISIBLE_DEVICES=0 ns-train monosdf --pipeline.model.sdf-field.use-grid-feature True --pipeline.model.sdf-field.hidden-dim 256 --pipeline.model.sdf-field.num-layers 2 --pipeline.model.sdf-field.num-layers-color 2 --pipeline.model.sdf-field.use-appearance-embedding True --pipeline.model.sdf-field.geometric-init True --pipeline.model.sdf-field.inside-outside True  --pipeline.model.sdf-field.bias 0.8 --pipeline.model.sdf-field.beta-init 0.1 --pipeline.datamanager.train-num-images-to-sample-from 1 --pipeline.datamanager.train-num-times-to-repeat-images 0 --trainer.steps-per-eval-image 5000 --pipeline.model.background-model none --vis tensorboard --experiment-name monosdf-htnt-scan1 --pipeline.model.mono-depth-loss-mult 0.001 --pipeline.model.mono-normal-loss-mult 0.01 --pipeline.datamanager.train-num-rays-per-batch 2048 monosdf-data --data highresTNT/scan1 --include_mono_prior True

**Comment by niujinshuchong** [comment]
Hi, when dose the error happen? After how many iterations?

**Comment by niujinshuchong** [comment]
Hi, I think you should use the sdfstudio-data parser instead of monosdf-data parser because sdfstudio-data parser will choose how to set near and far planes from the meta-data while you might need to set the near and far plane from the command line with monosdf data. Please refer to https://github.com/autonomousvision/sdfstudio/blob/master/docs/sdfstudio-data.md#Dataset-format for more details.

**Comment by BingHanOfUESTC** [comment]
Thank you for your nice work and patient answer. Looking forward to your more exciting work.
