### ISSUE TITLE
Import error when using instant-ngp

### ISSUE THREAD

**Issue by ZiyangYan** [autonomousvision/sdfstudio#46]
Everytime when I want to using instant-ngp method, I will meet a problem like this

ImportError: cannot import name 'csrc' from 'nerfacc' 
![image](https://user-images.githubusercontent.com/92861079/219936843-670331aa-107e-4d2b-9db6-5e8c42bdc2f9.png)

how to solve it?

my command is: ns-train instant-ngp  --pipeline.model.background-color white --vis viewer --viewer.skip-openrelay True --viewer.websocket-port 7007 --experiment-name with_white_background_50 instant-ngp-data --data /home/zyan/Downloads/data/with_white_background/images_50/

**Comment by niujinshuchong** [comment]
Hi, instant-ngp use nerfacc. Maybe you could follow this issue https://github.com/KAIR-BAIR/nerfacc/issues/156

**Comment by ZiyangYan** [comment]
> Hi, instant-ngp use nerfacc. Maybe you could follow this issue [KAIR-BAIR/nerfacc#156](https://github.com/KAIR-BAIR/nerfacc/issues/156)

I solve it through uninstall nerfacc and then "pip install git+https://github.com/KAIR-BAIR/nerfacc.git" to build the wheel together when installing

**Comment by rohit7044** [comment]
I was having the same problem in windows.
Then I found this step  [#238](https://github.com/nerfstudio-project/nerfacc/issues/238#issuecomment-1975497748) which mentions adding MSVC to path. 
Worked like a charm
