### ISSUE TITLE
Support for different intrinsics for every camera

### ISSUE THREAD

**Issue by coreqode** [autonomousvision/sdfstudio#48]
We have a dataset from a multi-camera capture system with different intrinsics for every camera. SDFStudio currently supports only one intrinsic as of now. Is there a way to enable multiple intrinsics?

When I try to update the meta-data.json with an array of intrinsics, it gives an error.

**Comment by niujinshuchong** [comment]
Hi, per-image intrinsics are supported. Please check the code here https://github.com/autonomousvision/sdfstudio/blob/master/nerfstudio/data/dataparsers/sdfstudio_dataparser.py#L200-L210. Maybe you should put the intrinsics under different images.
