### ISSUE TITLE
Understanding noise in depth map in NeusFacto v.s. MonoSDF

### ISSUE THREAD

**Issue by pablovela5620** [autonomousvision/sdfstudio#5]
So I've been trying to understand how NeusFacto compares to other methods specifically for indoor. I've noticed that for NeusFacto does a much better job in image quality, but there's a strange amount of noise specifically in the depth reconstruction. I've shared examples on a room I captured using Polycam.

https://api.wandb.ai/report/pablovela5620/psjincx1

Would love to know if ya'll have any insight on this. Is this mostly a problem with the rendering method of Neus v.s. VolSDF?
I also noticed this issue when I tried experimenting with Highres tanks and temples on Neus-facto v.s. monosdf.

Heres NeusFacto
<img width="785" alt="image" src="https://user-images.githubusercontent.com/25287427/209444042-37afe737-88e7-4474-856b-d4efe0c01513.png">

and here's MonoSDF

<img width="782" alt="image" src="https://user-images.githubusercontent.com/25287427/209444055-d13708c9-a099-43b8-9702-ad58d1d9eda7.png">

**Comment by niujinshuchong** [comment]
Hi, are you using the same network configurations for all of them? Looks like you are using feature grid for neus-facto while using pure MLP for all others?

**Comment by pablovela5620** [comment]
looks like they're all using hashgrid. This is what the config.yml file looks like for all of the runs
<img width="488" alt="image" src="https://user-images.githubusercontent.com/25287427/209450685-17b82a3b-bd5f-4b73-b8ef-46f372a37c94.png">

Though I did notice that the background model for Neus-Facto is `None` while for all others its `MLP`. Are you talking about the sdffield? or the background model
<img width="553" alt="image" src="https://user-images.githubusercontent.com/25287427/209450733-cd7909ee-ed34-49bb-b2b2-4119a68d70fd.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/25287427/209450738-26de9dc4-c870-4622-86d3-f66e1a08f3d0.png">

**Comment by niujinshuchong** [comment]
Hi, I mean the use_grid_feature in sdf_field. It's false in your screenshot. I think I should update it so that we can set encoding_type to none when we don't want use feature grid. Now it's a little bit confusion because we have two attribute use_grid_feature and encoding_type.

**Comment by pablovela5620** [comment]
Ah okay I see, yea. So that swirl type pattern that seems to appear in the depth images is due to using the hashgrid instead of the MLP? Is this something that goes away with enough iterations? From some testing I was doing it seemed to lead to some floater artifacts, I remember in the MonoSDF paper reading that MLP gives slightly better accuracy v.s. hashgrid. Is this where that shows up?

**Comment by niujinshuchong** [comment]
Hi, I think it gets better in the end if the model converges but the artefacts won't completely go way. Yes, we found in MonoSDF that feature grids tends to produce noise results or artefacts compared to pure MLP, but it also converges faster and brings more details. It's a trade off here and maybe we need better regularization.

**Comment by pablovela5620** [comment]
Understood, thank you for the insight. I'll do some more investigation/testing.

**Comment by pablovela5620** [comment]
I did find this in the recent NeuS2 paper

<img width="577" alt="image" src="https://user-images.githubusercontent.com/25287427/209456412-cc48da0f-ec95-44ba-87ef-bf3dffc5c596.png">

Seems like an interesting potential direction. Would love to see both [NeuS2](https://vcai.mpi-inf.mpg.de/projects/NeuS2/) and [NeuRIS](https://github.com/jiepengwang/NeuRIS) integrated into SDFStudio

**Comment by XianSifan** [comment]
> So I've been trying to understand how NeusFacto compares to other methods specifically for indoor. I've noticed that for NeusFacto does a much better job in image quality, but there's a strange amount of noise specifically in the depth reconstruction. I've shared examples on a room I captured using Polycam.
> 
> https://api.wandb.ai/report/pablovela5620/psjincx1
> 
> Would love to know if ya'll have any insight on this. Is this mostly a problem with the rendering method of Neus v.s. VolSDF? I also noticed this issue when I tried experimenting with Highres tanks and temples on Neus-facto v.s. monosdf.
> 
> Heres NeusFacto <img alt="image" width="785" src="https://user-images.githubusercontent.com/25287427/209444042-37afe737-88e7-4474-856b-d4efe0c01513.png">
> 
> and here's MonoSDF
> 
> <img alt="image" width="782" src="https://user-images.githubusercontent.com/25287427/209444055-d13708c9-a099-43b8-9702-ad58d1d9eda7.png">

Hello, I would like to ask how to export depth map in sdfstudio, does it provide an interface?
