### ISSUE TITLE
Remove webrtc from nerfstudio viewer

### ISSUE THREAD

**Issue by lucasthahn** [autonomousvision/sdfstudio#63]
#### Problem
The viewer often suffers from showing as `Server Connected`, but `Render Disconnected`, and will not render any images (also see #31)

#### Proposed Solution
The Nerfstudio folks recently fixed this issue by removing webrtc entirely from the viewer and sending everything over TCP. I'd like to propose that this project also follows suit for improved viewer stability. I'm happy to do it myself and submit a PR if that's ok! [This](https://github.com/nerfstudio-project/nerfstudio/pull/1014) is the PR that fixed the issue.

**Comment by niujinshuchong** [comment]
Yes, PRs are welcome.

**Comment by lucasthahn** [comment]
Thanks! Closing this issue as it is effectively a duplicate of #31
