### ISSUE TITLE
Only showing cameras but not the render

### ISSUE THREAD

**Issue by DavidNP96** [autonomousvision/sdfstudio#67]
I am only seeing the cameras but not the render itself when following the intro tutorial.

I am running the intro example of the skull on a google the remote compute engine.
after cloning the repo, installing dependencies and port forwarding to port 7007 I expected to get this result:

![image](https://user-images.githubusercontent.com/44022245/226862776-50892abc-569e-4adb-a0d9-0d3ddf95bc65.png)

However I find this:

![image](https://user-images.githubusercontent.com/44022245/226863862-8f92ec91-1c32-4ead-87a2-d2cc3f09d54a.png)

A similar issues occurred in the nerfstudio project itself and where fixed by removing webrtc. (see: https://github.com/nerfstudio-project/nerfstudio/pull/1579). I tried the nerfstudio tutorial itself and it indeed worked as expected. 

Any suggestions?

**Comment by salykovaa** [comment]
Hi @DavidNP96 
Try to run sdfstudio with using the commit from #65 This should fix the issue

**Comment by DavidNP96** [comment]
@salykovaa Yes thank you this works!
