### ISSUE TITLE
How to run and debug through an IDE?

### ISSUE THREAD

**Issue by A-Hexa** [autonomousvision/sdfstudio#75]
Hi,
I would like to run and debug train.py through an IDE. How can it be done?
How should I configure the script parameters and Docker container settings? 
Are there any changes needed in the code?

**Comment by niujinshuchong** [comment]
Hi, you could refer to https://github.com/autonomousvision/sdfstudio/blob/master/.vscode/launch.json#L42-L64 to config the debug environment with vscode. Note that the current launch.json is not up to date so it might not work anymore.

**Comment by A-Hexa** [comment]
Thanks a lot.
