### ISSUE TITLE
How are `pairs.txt` generated?

### ISSUE THREAD

**Issue by pablovela5620** [autonomousvision/sdfstudio#77]
I want to be able to use the photo metric multi view consistency with a custom dataset for Geo-Neus. How would I go about generating it?

**Comment by niujinshuchong** [comment]
Hi, the pairs.txt for dtu dataset is copied from NeuralWarp. You could refer to https://github.com/fdarmon/NeuralWarp/issues/1 and https://github.com/GhiXu/Geo-Neus/issues/1 for more details.

**Comment by pablovela5620** [comment]
Perfect, thank you
