### ISSUE TITLE
ImportError: cannot import name 'OccupancyGrid' from 'nerfacc'

### ISSUE THREAD

**Issue by flycooler** [autonomousvision/sdfstudio#80]
After following the installation process, when running "ns-download-data", the error shows up:

\nerfstudio\model_components\ray_samplers.py", line 25, in <module>
    from nerfacc import OccupancyGrid
ImportError: cannot import name 'OccupancyGrid' from 'nerfacc'

Any suggestions for idea? Thanks!

**Comment by xyzhang77** [comment]
nerfacc has been updated to v0.5.0. v0.3.5 may be OK. See https://github.com/KAIR-AIR/nerfacc/blob/master/CHANGELOG.md for details

**Comment by alan355** [comment]
> nerfacc has been updated to v0.5.0. v0.3.5 may be OK. See https://github.com/KAIR-AIR/nerfacc/blob/master/CHANGELOG.md for details

Sorry, the link you give can't open. Could you explain it again?

**Comment by alan355** [comment]
Thanks

**Comment by flycooler** [comment]
Thanks a lot for the kind responses! Yes, **OccupancyGrid** got renamed in nerfacc 0.5.0, and downgrade nerfacc version to v0.3.5 works.

**Comment by Miaosheng1** [comment]
This Command works:

> pip install nerfacc==0.3.5

**Comment by Ira569** [comment]
Thanks
