### ISSUE TITLE
cannot close port connection 7007

### ISSUE THREAD

**Issue by DavidNP96** [autonomousvision/sdfstudio#81]
Hi all,

I am working on a remote compute instance. I ran the training script and it was working. However, The ssh connection crashed in the middle of training and I cannot just detach from the port connection anymore. when I run the training script It tells me to  change the websocket port, but I rather just be able to clear this connection, so that I not constantly have to change the ports. Does anybody know how to clear the port 7007 connection?

**To Reproduce**
ssh into the remote instance where sdfstudio is running.
runt the train script as per documentation. 
wait till ssh connection fails and reconnect.
run train command again and observe the error

"The viewer bridge server subprocess failed. Please check the log file outputs/neus-facto-replica1/monosdf/2023-04-11_082945/viewer_log_filename.txt.
You likely have to modify --viewer.zmq-port and/or --viewer.websocket-port in the config to avoid conflicting ports.
Try modifying --viewer.websocket-port 7007"

**Expected behavior**
I would expect that the viewer disconnect when ssh connection crashed or that there is a way to force the viewer to disconnect from the current port

**Screenshots**
This image shows the viewer is still connected to port 7007
![image](https://user-images.githubusercontent.com/44022245/231106780-e37c750b-d29e-4254-b9fd-be9891cd1f6c.png)

However my terminal looks like this

![image](https://user-images.githubusercontent.com/44022245/231107116-1a49bb07-4d90-4116-a33a-1e89d8995604.png)

**Comment by yangeer** [comment]
How did you finally solve it?
