### ISSUE TITLE
Sparse points loss?

### ISSUE THREAD

**Issue by sergiobdrl** [autonomousvision/sdfstudio#9]
In the GeoNeus paper, one the losses is what the authors call the "View-aware SDF loss" (eq. 15 in their [paper](https://arxiv.org/pdf/2205.15848)). 
Is this implemented somewhere in this repository? I can only find references of the patchmatch loss, but no code related to the SDF loss. Am I missing something? Is there any implementation plan for this?

Best,

Sergio

**Comment by niujinshuchong** [comment]
Hi, the "View-aware SDF loss" is not implemented but seems like straightforward to add it. Will add it soon hopefully.

**Comment by niujinshuchong** [comment]
Hi, the "View-aware" SDF loss is added now.  You need to download the latest data and code. It can be run with
```bash
ns-train neus --pipeline.model.sdf-field.use-grid-feature False --pipeline.model.sdf-field.hidden-dim 256 --pipeline.model.sdf-field.num-layers 8 --pipeline.model.sdf-field.num-layers-color 4 --pipeline.model.sdf-field.use-appearance-embedding False --pipeline.model.sdf-field.geometric-init True --pipeline.model.sdf-field.inside-outside False  --pipeline.model.sdf-field.bias 0.5 --pipeline.model.sdf-field.beta-init 0.3 --pipeline.model.sparse_points_sdf_loss_mult 1.0 --trainer.steps-per-eval-image 5000 --pipeline.datamanager.train-num-rays-per-batch 1024 --pipeline.model.background-model none --vis wandb --experiment-name neus-dtu63-sfm-points  sdfstudio-data --data data/dtu/scan63 --include_sfm_points True
```

**Comment by sergiobdrl** [comment]
Amazing! Thank you for this. Will test ASAP.
