### ISSUE TITLE
Cannot get a decent surface model of a potted plant

### ISSUE THREAD

**Issue by suptimq** [autonomousvision/sdfstudio#91]
**Describe the bug**
I am trying to train a SDF model on a potted plant that was captured in a greenhouse. I can achieve decent results using nerfacto and even vanilla-nerf. I tried a couple of different setups for this, including

1. neus-facto
2. volsdf
3. volsdf with foreground masks
4. volsdf with depth and normal

The model can reconstruct the radiance field (i.e., RGB information) ok but completely failed to reconstruct normal and depth with all the above setups.

**Eval Images**
![image](https://user-images.githubusercontent.com/29498118/233513515-28a855c4-11c0-4db2-b4c6-b60486bfad31.png)

**Training**
![image](https://user-images.githubusercontent.com/29498118/233513622-c0eeab8b-3443-421c-8242-1eea0049fff2.png)

**Eval**
![image](https://user-images.githubusercontent.com/29498118/233513675-2258311e-e4fe-4112-981b-d94206e2ec01.png)

**To Reproduce**
Here is the [dataset](https://drive.google.com/drive/folders/1zhO-NDaZIUS1T28aGgYZc10G3qWdgWxs?usp=sharing)
Here is the command

```bash
ns-train volsdf --pipeline.model.sdf-field.use-grid-feature False --pipeline.model.sdf-field.inside-outside False --pipeline.model.sdf-field.bias 0.5 --pipeline.model.sdf-field.beta-init 0.1 --pipeline.datamanager.train-num-rays-per-batch 2048 --pipeline.model.background-model mlp --pipeline.model.near-plane 0.2 --pipeline.model.far-plane 8 --pipeline.model.overwrite-near-far-plane True --trainer.steps-per-eval-image 2000 --trainer.max-num-iterations 100000 --vis wandb --experiment-name VolSDF_r2l1_nerfstudio-data nerfstudio-data --data data/nerfstudio/r2l1 --downscale-factor 2
```

**Comment by niujinshuchong** [comment]
Hi, your images is looking forward and the object is not centered. Maybe you could refer to https://github.com/autonomousvision/sdfstudio/issues/51.

**Comment by suptimq** [comment]
Thank you for the quick response! I will merge this PR https://github.com/autonomousvision/sdfstudio/issues/51#issuecomment-1517059174 to my local codebase and switch to 'foucs'.

Also, I wondered if the plant's geometry (i.e., tiny branches) is intrinsically hard to learn. Or do you expect at least we have something meaningful for normal and depth while not being perfect?

**Comment by niujinshuchong** [comment]
@suptimq I think at least it won't fail completely.

**Comment by suptimq** [comment]
That makes sense! I quickly fixed the center options and definitely got better results shown below:

![image](https://user-images.githubusercontent.com/29498118/233722582-b8ed51d1-c8b5-48e8-b1f3-356d10e46afd.png)

Additionally, I trained another volsdf model on another plant and got decent results with some blurry effects:

![image](https://user-images.githubusercontent.com/29498118/233723055-98fddd69-fa39-4794-b0e3-4a88ecc3c607.png)

While these two models demonstrated ok results, I wondered if you have any suggestions for me to further improve the reconstruction of details. For instance, the tiny branches in the first plant and the leaves in the second plant.

**Comment by niujinshuchong** [comment]
@suptimq Your rendering results look promising. If you capture your images, having more images from many different viewpoints would be better.

**Comment by suptimq** [comment]
@niujinshuchong, thanks for the suggestion! Other than the data-side augmentation, I am particularly interested in your suggestions in terms of the model parameters as well. Also, I observed from a bunch of experiments that most sdf models tend to produce smooth objects' surface very much, making details missing on the surface. I wondered if it is due to model parameters or if it is due to loss functions. Are there any ways to make details more evident?

**Comment by niujinshuchong** [comment]
@suptimq You could try to decrease the weight for eikonal loss, increase the network size, or enable multi-res. hash encoding.

**Comment by suptimq** [comment]
@niujinshuchong I will give it a try and close this issue. thanks for the help!
