### ISSUE TITLE
mesh output has low quality mesh, how to fix it?

### ISSUE THREAD

**Issue by D-Mad** [autonomousvision/sdfstudio#92]
i trained on nerfstudio poster data, i converted the data to sdfstudio and train, and my mesh output low-poly, i trained with default 20000 steps, what do i need to adjust when exporting to get high poly or do i have to train more step ?
![scan1](https://user-images.githubusercontent.com/8207507/233570737-687ab819-34da-4ea9-af5e-5431b64910eb.png)

**Comment by niujinshuchong** [comment]
Hi, do you mean increasing the resolution of meshes?
