### ISSUE TITLE
How to optimize the camera poses.

### ISSUE THREAD

**Issue by XuqianRen** [autonomousvision/sdfstudio#95]
Hello!
Thank you for releasing this amazing codebase! I have one question

I noticed that in the method_configs.py, every sdf-based pipeline turned off the camera_optimizer, I want to ask why the pipeline can't optimize the camera poses at the same time. 
```
camera_optimizer=CameraOptimizerConfig(
                mode="off", optimizer=AdamOptimizerConfig(lr=6e-4, eps=1e-8, weight_decay=1e-2)
            ),
```
When I tried to train a dataset with the mode="SO3xR3", I found the pose is a little bit rotated from the right input pose, like shown in this picture. The left is the real image, the right is the rendered one. But when turn on this option in nerfacto it works very well. May I ask how I can set the parameters properly to make the pipeline also optimize the camera poses at the same time?
![image](https://user-images.githubusercontent.com/84827495/234563265-b9e2b9bf-497a-4cd1-8df3-4ad7d046960a.png)

**Comment by niujinshuchong** [comment]
Hi, pose optimization should work with sdf-based method. But maybe nerfacto converges faster than sdf-based method, so the hyperprameters (e.g. lr) tuned for nerfacto is not optimal for sdf-based methods. You could try to use a smaller lr.

**Comment by XuqianRen** [comment]
Thank you for your reply. I have solved this problem.
