### ISSUE TITLE
occupancy grid based pruning

### ISSUE THREAD

**Issue by slpmee** [autonomousvision/sdfstudio#97]
Hi, 
I have a question of occupancy grid based pruning in ray sampling.
There is a comment about negative effect of density based occupancy grid in ray_samplers.

Does density based occupancy grid cause crash and damage quality only on surface reconstruction not view synthesis? 

https://github.com/autonomousvision/sdfstudio/blob/fc6fdab4e9b9d24391228c95456c6ccab94bef64/nerfstudio/model_components/ray_samplers.py#L458-L465

**Comment by niujinshuchong** [comment]
Hi, this part is implemented in nerfstudio and it's not used for surface reconstruction. We have implemented neus-acc which also use nerfacc's ray marching and empty space skipping. Please check it here: https://github.com/autonomousvision/sdfstudio/blob/master/nerfstudio/model_components/ray_samplers.py#L1315

**Comment by slpmee** [comment]
I didn't chect that part. Thanks a lot.
